<?php

function main()
{
    $board = readBoard();

    $resultUD = solveUD($board);
    $resultLR = solveLR($board);

    $result = count($resultUD) < count($resultLR) ? $resultUD : $resultLR;
    writeResult($result);
}

// function main()
// {
//     $board = randomBoard();
//     $resultUD = solveUD($board);
//     $resultLR = solveLR($board);
// }

// function randomBoard()
// {
//     $board = [
//         [1, 2, 3, 4],
//         [5, 6, 7, 8],
//         [9, 10, 11, 12],
//         [13, 14, 15, 0],
//     ];

//     for ($i = 0; $i < 1000; ++$i) {
//         list($x, $y) = locationOf(0, $board);
//         $cands = [];
//         if ($x != 0) {
//             $cands[] = [-1, 0];
//         }

//         if ($x != 3) {
//             $cands[] = [1, 0];
//         }

//         if ($y != 0) {
//             $cands[] = [0, -1];
//         }

//         if ($y != 3) {
//             $cands[] = [0, 1];
//         }

//         $r = [];
//         step($x, $y, $cands[rand() % count($cands)], $board, $r);
//     }

//     return $board;
// }

function readBoard()
{
    $board = [];
    $lines = file('php://stdin', FILE_IGNORE_NEW_LINES);
    foreach ($lines as $l) {
        $b = explode(' ', $l);
        foreach ($b as &$e) {
            if ($e == '*') {
                $e == 0;
            } else {
                $e = intval($e);
            }
        }
        $board[] = $b;
    }
    return $board;
}

function solveUD($board)
{
    $goal = [
        [1, 2, 3, 4],
        [5, 6, 7, 8],
        [9, 10, 11, 12],
        [13, 14, 15, 0],
    ];
    return solve($board, $goal);
}

function solveLR($board)
{
    $board = array_map(null, $board[0], $board[1], $board[2], $board[3]);
    $goal = [
        [1, 5, 9, 13],
        [2, 6, 10, 14],
        [3, 7, 11, 15],
        [4, 8, 12, 0],
    ];
    return solve($board, $goal);
}

function solve($board, $goal)
{
    $strategies = [];

    $strategiesForUpperTwoRows = [
        'dirLRandPackR',
        'dirLR2',
        'dirLR3',
        'dirLR4',
    ];

    foreach (range(0, 1) as $y) {
        $strategies[$y] = [];
        foreach ($strategiesForUpperTwoRows as $s) {
            $strategies[$y][] = function ($b) use ($y, $s, $goal) {
                return call_user_func($s, $y, $b, $goal);
            };
            $strategies[$y][] = function ($b) use ($y, $s, $goal) {
                return flipStrategyDirection($s, $y, $b, $goal);
            };
        }
    }

    $strategies[1][] = function ($b) use ($goal) {
        return optimalSolverForSecondRow($b, $goal);
    };

    $strategies[] = [
        function ($b) use ($goal) {
            $result = lowerTwoRowsFast($b, $goal);
            return [$result, $b];
        },
    ];

    $best = false;
    foreach (cartesianProduct($strategies) as $chain) {
        $b = $board;
        $r = [];
        foreach ($chain as $s) {
            $sres = $s($b);
            if ($sres !== false) {
                list($rnext, $b) = $s($b);
                $r = array_merge($r, $rnext);
            } else {
                $r = false;
                break;
            }
        }
        if ($r !== false) {
            // echo 'Length = ' . count($r) . "\n";
            // printBoard($b);
            if ($best === false || count($r) < count($best)) {
                $best = $r;
            }
        }
    }

    return $best;
}

//////////////////////////////////////////////////////////////////////

function lowerTwoRowsFast(&$board, $goal)
{
    $data = 'EABEgBABRIAQEQSAzAxExAARQIQRAESEAAEyohEBRIABAETAEREAgEgMAIQAEUCEERBEgBAAIrIBAACAAABAwAARAISMCISIIjJIhCIyxIwiMiOiRIQREUSEEQFEgBEBIuIREQDAABEEwBEAQIBEDESEERFEwBEBRMQBASKzEQBEgAARQIQQAESAiAxEgBEAAIAAAADEABEyoTMyRIQiEsiEEjFEjMwIEBFEhBERRIQREUSEiAgAhAARQIQRAUTEAREisREARIARAADAEAEAgMgMRIQBEQCEERBExBERI7IAEUCEABFEgBERAITMCIiMIhGIhDEzRMwTETKzRIQREUSEEREEhBERIqIREUCEERFEhAEQAITMCESAEQBEgBABAMQAETKzEREEhBERRIQREESAiAhAhAAAAIAAEEDEARAyoyIjxIwTMYzIEzGIjMgIzAwzk8wMM/NEBDOzjAgRs8QEM5PMBBPxRAQyocwEM5HMBBGTRAwRs8wIM7FEBDOxxAwR0cwEI7FEBBGRRAQR0UQEEZFICMSMEzFEjDERzMwTMTOxRIARAEDEEAFAhAABEqIREQCEARFExBERQICMCECAAQBEwBABQIQAASKzEAFEhAERBMQREQSAiAgAgAABAIAQAACEABEi4xIzhIwiMojMMyGMiIgMEQFExBERRMAREUSETAxAhAAAQIQRAASAAAAz0xERRIQQAESEEREEwMwMBIQREEDEABBEgBEAE9IREETAAAAEwAARAMRECESMMRFMxCESRIwREhPTRIQREUTEERFEhBERIvIAAQDEABFAwBERAMCIBESEEQBEwAAABIQAACLTEREAxAARBMAREUTESAgAhAABAMQRAASEABET0yIziMQiEUzIERFExEQEERFEgBERRMQAEUTESAxAhBABRMARAQSEABET0xEQRMARAETEABAAxEQERIQAEQTAERFEgBEAE+IQEQDEAAAAwAEBAMCEBMyMESFEzDEihIQiMyLiM7HMBDPTzAwRscwMM9LEBBHTzAQz00QEEdNECDORzAQz0cQMEZFEBBPixAQR8UwEEfPEBDPRSAQRkUQEEdFEBBGRRAQi0zETRMwRM0zEMxFExEQEEQAEgAABRIAAEQDEiAQExAARAMARAQCEARER0wEARIAQAETAABEAxEgEAIQAEQDEARFEhBERE+IAEQDEAAFEwBERBIRICMiEIiNMxDEijIgiMiKiRIQREUTEEQFEhBERItMAAADAABEEwAARAIREDESEEQFEwAEAAIQBEROjEREExAARRMQREUSERAgEhBERAIQREUSEEREjozMTRIwSM0SIMSGEzMwIERFAhBERRMQRAUTAiAQAhAABAMAREUSAEQAToxERRMQRAEDEEQAAhEgMBIQAEETEEABEhBARE6IRAQCEABEEgBEAQISICIyEETFIhBEzzIwzMTKjBIAREUTAEBFEhBEREuIAEQCEERBAhAERRICMDESAEABEgAABRIQQECKjERFExBERRMQREETESAgEhAAARIQQAASEABAj4xMijMgiIUjIIjGIjIgITAQz8cwEMfPEDDOzRAwRs0QEE5HEDBGzxAQi48QEMZHMBBGTxAwRkcwMEbPMDDPxzAwzkcwEI/NEDBGRRAQR0UQMEbFMCESEMzHEzDERzIgRITPjIqAICCKiAAgAgogII6KICCKiiAgCoggIIIKICACgCAAg4oAIIKKICBPjiAgAgogIIuIAACCiSAwggIAIIOIACCCiiAgi0zMzzMwhMUjIIxPIxEgEgAgAgoAIAuKICCCijAwgoIgIIuCICCCAiAgT0wgIIOCICCLgiAAgoEQIIKKICCDgCAgggIgIE9OICCDgiAgi4ogAIoBECMSEERFEzCEiRIwxMSOjIIAACCDiAAgggogAMqKIACDiiAgC4IgAIqBECACgiAgg4IgIIKCICCLTgAAg4IgIIuCIACCgSAggoIgIIuCICCCAiAgS0yIziMwiEczMMxFMjEgMiAAAoogIAuKAACCiTAwgoIgIIOCICCCCiAgi04gIIOCICCLgiAAgoEQIIIKICCLgiAggoIgIE9OICCDgiAgi4IgAIqBECEyMMxFEyDERhIwRMxOiMZNEBDOTzAwxkcwEItJEBBHRRAQz80QEE5FIDDORzAQz0UQEEZFEBBOyRAQR8cQMEdHEBDGRRAwRkUQMEbNEBDGRRAwjozMTTIwRIkSEIzHEiMwMAIARAQDAEAFAhAARE7IBEACAAAFEgAARAITMDESEEQFEgBEAAIQAASOzEBEAhAABRMQREQSASAxAhAARAIAREACEEREyojMjzIQhMYzIEyLIiEgIEQBEgBERRIAAEUCEjAwEgBAAAIAAAADEABEz0RERRIQRAASAAREExMgEQIQAEQCEERFExBERI9IREQTEAAFExBERRIRECMTEERFMzDEiRIgiMiOyQIQREUSEERFEgBEQIqIREQCEEAFExBEABMCMBESEEQFEgBEAQMAAASLREQAEgAERQIAQEUDEiAhEhAABAMQQAATAABASoTMzjMQiEczMEzFMjEgMEBFEgBERRIQAEUSEjAhAwAARBMABEUDEEREToQEARMARAEDEAREAhEgMRIQREUSEERFEwBEAI6EAEQCEARBEwAERBIRICISIMSJIiCIiiMwiMyLiMbHEBDORzAwRs8wMIqJEBBHRTAQR88QMM7NICBHRxAQz0cQMEdNEBBPixAwRs0wMM7PMBDORiAwRsUQMEZFEBBPzRAwiozMzTIwTM8zEMyJEiEwMABEExBARRMQREUSERAwEhAABAMQREUSEERETshERRMQRAUTAERFAhEgMRIQREUSEERFEhBERM/IREUCEARFEwBERAIRMCESEExJIhCESRIgSMjKiRIAREETEEABAhBABErIRAADAABAAwAAAAIBEDECEABEAwAEABIABEBKzEBEEhAAAAMQRAASAyAwEgBEAAMAAAACAARAyoxMzRIQTEczEEzFEhEwMERFEhBERRMQREUSAjAxEhAAQQMQBAASAAQAzsxERRIQRAADEAQAEgMgMBIAREACEAABAhAERM7IBEQCEABEAgBEAQIDMCMiEERFIhBETRIwTETKzQIQQEUSEERFEhBERMqIAEQCAERAAhBEBQITMCETAEQAEgAARQIQBEDOzERFAhBERBIQRAESAyAxAhAEQAIAAAACEARAysxIiRIgSEcyEEhFIhMwMxAwRs8wEM/NMDDOzTAwRk0QEE5FEDBORxAQys8wEM5FMBBGTRAwRkcwMM7NEDDORTAwTkUwEM7NEBBGRRAQRkUQMEbHMCMSMEzFEhBERRIgRETOzAIQREQCEERFEhBERIuIREQCAAABExBERRIRMCESEEQFEwBEBQIQBESKyERFAhAERRMQREUTASAhEhAERAIAREUSEEREiojMiRIgiIkjIIiKIiIgIERBEgBERRIAQAEDAjAREwAAABIQAAACAAQAz0xERBIQAAACAAREEwMgEQMABAADEAABAgAAAM/MRAATAAAAAwAAAAISICMSEExFIhBITyIwRMzPTRIQREUSEERFEhBERIrIQEQCEERAAxBEBAMDMBESEEQAEwAAAAIAAABLTERFEhAERAIQREUTEyAhEhAARAMQRAASAARAS0yITxMwTEUzIEzFMxEgEARFAxBERRMQREUSERAhAhAERBMQREASAERAT0hEARMARAADEAAAAwEgERIQREATEAQEEgBEAI9IBEQDEAAAAwBEBAIRMCEiMIhNIxDMTRIwSExLTEbPEDDOzzAwzs8wMMtLEDBHRTAQT0UwEMbFEDDORTAQz0UQMEZFEBBPTzAwzsUwEEdFEBBPRSAQRsUQEEdFEBBORRAQS0xMjTMwREUzEEhNExEwEiAgggogAAqIIAAKCzAggogAAIIIICAKACAAyoggAAKIICALiCAAiokwMIoAIACKggAgAggAIIrKIACKAiAACooAIIICICISIEiJIjCIiiIgiIjKjAoCAACLiAAACgoAAEqKICCCiiAgC4ogAIoLMCACgiAgg4gAIIoKICBLziAgioogIAuIIAACCiAwigIAAIoIACACCgAgy0zMzRIwTE8zEExFExMwECAACggAAAqKAAACCiAwigIAAIqIACACCgAAzswgIIOKACCLigAAi4kwEAICACCLiAAgggoAIE/KAAADiiAgi4oAAIoJMCIiMEhNExBEzRIwTMRPTAoCAACKAAAgAgoAIMqKIACLigAAC4oAAIoLMCACAgAAi4oAIIIKACBPTgAgAgogIAuKAACLiSAwAgIAIIuKACCCCgAgSszIixIgRE0zEEhFEzEwIzAwzs8wMM/PMDDPzSAQRkUQEEZFEBBGRRAQz08wEM5FMBBHRRAQR0UwIM/NEDBPxRAQTkUQEM9PMDBGTRAwT0UwEEbFICMyIEzJEyDIRSIwRIRPTIgEIiCIgRIghEIiIjAiIiAIiiIASIEiIIRAj8gEBQIABIITIASKIgMwICIABEgiAIgBAhAAiIqIhAgSIIgCEyAIiiICICISIMSKEiCIiiIwjESPzBIgREADIEAAIiAEgI/IBAYCIAiEAiCEiiIjMDACAASEAiAAhiMghATKiAQKIiCEBCIACIQiIiAwIgCEiiIgCIojIIgIyozEiRIQTMoiIEzPExIwEAQIIiAEARIACEACAiAgIiCEiiIgiAQjAAAEioQEBAIABIQDIAQEIiIgMCIAiAYiAAAEAwAEBI6EBAYCAACEAyAEBgIBICIiMIjGIhDEzzMwzEyLRCIARAAiAECIEiCIAIqIBAYiAIQEAiAECAIiICACAASIIyAIhCMAhABOiAQKAiCIBCIACAQCIiAwAgCEiiIgCAAjAAAEioTMzzIwyI8zEMzGEzIwIxAwT88wMM/PMBDORSAwRs0QMEZPMDDPRRAQi08wEM5HMBBHRRAQR0UwIM5FEBBOxRAQR0cQEI9FEBBHRRAwx0UQEEZFECMzEMxPEyCERRMwRMxOiAIgBAgjIEiAIhAIgErIBAgjIIQJIwCIQAIRICAiAEQAAyBAigIgiIDOyAgEAgCABBMAREESIyAyIhAICCIgQIISIIhAjsiISTIwSIojMMiNIhEgMIgEAwAAgRMgAEICIRAwAiCECiMAiIgCEAiIT8wEgiMAhIoTAACIAiEQMgIACIgCAEiJAhAIiI9MgEQjEIiKEiBEChIDMCMyMERFMxDETRIwRERPTCIQCEADAECCEhBEgIvIgAQDIIiJEiBIShIjMCACAASKAiCIihIQiIjPzERGEgCIihIghIISIyAwEgCEiiIggIoSEIiIy8yIzRMwREUzEEzFEhMwMABEAhCIgBIgREIiIzAiIhAIiAIQQIgSEIhIz0hERhMgiIoSIIiCEiMwMBIAiIoiAICKAhCIiMvMREYSIIiKEiCIihIjICMSMERNEjDMRTIwREzOyM7PMDDOzzAwTscwEI/JEBBGRRAQR0UQEEZFMDDORTAQTkUQEEZFEBDOyTAQRkUQEEdFEDBGRyAwRk0QMEfNEBDORRAQyozMyRIQRE0yEEjNEjMwMASJIyCEARMgiEIjISAwIgCEiCIASAASIACIi0hEiAMgAIIjIIhCAiEgICMAQAgjAEABEiAIiE9MCIgiIIgKIyCIRgICICMyEIhOIzDMRzIwRMhOiBIARAADIEACEhAAAItIBAYSIIiJEyAEiiMDMBADAIiKEyBIihIQhADLSEQGEwCACBMARIgjATAQAiCICiIAiAACEABIiszMTRMQTE0zEMzFEhEQMASEEiCAARMASEIDISAxAhCIChIgSIASEIAIy0xECgIgiIoTIIiKIwEwERIAgIojAEiKAhCICE9ICIAjAICKAwAASAIBECMyEMxFExBEzyIwTERKzAIgAAojAEiAIhCAQMrIBIAjAIgKEwAASAIRIDAiIIQKIwCIiAIQCIhOzAgEAgCIChIAREoSIyAyIhAIiAMgSIgSEIhIiszMzTIwREUzEIzFMhEwMzAQz0cwMEdHEDBGTRAwRkUQEEdFEBBGRRAQSs8QEEdFEBBHRTAQRkUQMEZFMDBGRRAwzkUQEM7NEBBORRAQR0UQEEbFMCETEEhFEhDERRIwTIzKjIIAICCDiAAgCgogII/KIACDiiAgC4gAAIIJIDACCAAgg4gAIIoKICBPSgAgAgogIAuIACACCzAwgoogAIuKICAKAiAgSojEzjIQSIszEMzPEjEwIAAAA4ogIAuKAACCCSAwAoIAAIuIACCCCiAgTswgIIuKACALigAAggsQMAICACCKAAAgAgggIM7OICCKiiAgC4ggAIoBMCMzEERFEhDERRIwTMzOiAICAACLiAAgAgogII6IIACKigAgC4oAAIqJMDACgAAgi4gAIIIKICBOzAAgi4oAIAuIAACCiyAggoIgAIuIACCKCiAgS8zMzTIQREcyMEzFMxMgEiAgggogAAuIIACKCTAgg4IgIIqIACCKCCAAysggIIKKICALiiAAioswMIoCIACKgAAgAgoAIIrKIACKCiAACooAAIIKICMSMEzNEhDMTzIwTMzKiMZHMBDOzxAQRkUQEIrJEBBGRRAQR0UQEEdHICDHRTAwRkUQEEZFEBDPSRAQRkUQMEdFEBBHRSAQxkUwEEZFEBBGRRAQioyMzSIwRM0zEMzNMjEgIAqEAAAKhRAABkAAIMqIAABKAAAAAgAAAAJHMCBGhRAAA4QQAEYCAADOzAAQAkAAEAJBABBGgiAwhkoAIIpIICCKAiAQi4jMzRIwzEojMIyLMhEwMQAARgQQAEKEACAGgjAgR0QQAAMFECAHgCAgRsUQEAMEECBDBAAABkUgIEZAAAAGQQAQC4QAII7FACAGiiAgi4ogAIoCICMSMETHMjDETzMgxETOzAJAAABGARAQAkUQAIqIIACGAAAAAkUAEAJGMCAGhQAQRoQQAEdGACDPzQAQAgQAAEZEABAGRiAgikQgEIoBECBHQCAAyozMziIwzEczMEzFMhMgMQAQBkQAAEYBEAACAiAgRkQgEAZFEABHQCAAioUQEAaAACBCBiAQCkcgIEZCEAACRQAAQwQAAI/NIACKAiAAAwEAEAIFICMyIMyHMiCERSIwSEzOyEZHMBBGzzAwxs8QEIuJEBBGRxAQR0UQMEZFIDBORzAQzkUQEMZFEBDOyRAwRs0QMM5HMDBOTiAwRs0QMEZNMBBPzRAwyozMyzIgRE8iEMiFEiMwIRAgB0ggAEMFIBBKhRAgRkAgAANBABACRQAQiskgIAcFECBHABAACoEwMAKFABAGQBAQRgQQII9OICCKQCAgCwggAIpCICMyIMzKMyCIRiIgzMTPjAIFABBHBRAgRkQQAEtIEACKQAAQAokQIEuCMCBGBAAQCogQEEYCECCLTAAQQwAgEAMAEBADgSAgBkUAIIuKECCKAhAQi0xMzxMwzM8zMMxHExEQMAAQQkQQAEcEEBAGBiAwhoAgAAMBAAACQAAgT00QEAMIACCLAAAQA4kQEEZEABADABAABgAQAE+JEAADgCAAA4oQEIsCEBMiEIjGMxBEzxIwzESLTAZFECADBBAASkQAAItIIBBLgQAgQ4IQAAoCICBGRBAgA4gQAIoCEACLiBAQiwIAAAMAEBADASAQRkIQAIsCACACgAAgi0zMSzMgzIkjEIjGEzIQERAwxs8QMM/PMDDGRTAgRkUQEEZNEBBGTRAQz08wEM9HEBBHRRAQR0UQIEbNEDBHzTAQzscwME9NEBBHTRAwz0UQMEfNEBESMERFEyBERRIgRIhPiEaIACAGRRAgigQAAItIABAKAAAQQ0UAAEICICBGiRAgS4gAIIpGIABLiiAQhgAgEAMAEABDASAQigIgAIsAAAACQAAQiozMSjIgzIkjEIiKEhEwMQAQRgQQAAZEEBAHRiAQQkggIAMCECCKAiAQTs0QAAMAECCDAgAQgkIgIAZGABCLABAQRgAAEE7NEAACQiAQAgEQEAJCICMyEERHMiBERzIwRMTPjEYFEAACRRAAAkQAIItMIBCLAgAAQwEQIAJJIDBGABAAA4gAAAKIABBOzAAQAwgAAAuIAAAKQRAgAoQAEIICACBGiCAAj0yIzSIwxEcSMMRNMxMwERAAB0AAAEMFABACRRAwSgYgEAJAEAAGQQAAis0AIAYIABCKARAQQgMwIAJFEBADQBAARkgQAI9MABACAQAAQwgQEIJKMCESEIiHEyDEThIwSETPTEZPMDBPzTAQzs8QMErJEBBGRRAwxkUQEEdHIBDOTzAwxkUQEEZFMBDPTTAwz8UQMEfHMBDPRSAQzsUwEEdFEBBGxRAwT0xITzMQREUzEMRNEiEQICAAiogAAAuKAACCCiAwioIgAIqIACACCgAgj0ggIIIKACCLigAAggkwIAICACCKiAAgAoggIM9OACACiiAgi4ggAIoJMCMzEIxJMzCERTIgRIhGiAIAAACDiAAgggoAIEuKICCLgiAgi4IgAIuBEDCCgiAgg4IgIIICICBLTgAAi4IgIAuAIACDgRAwgoIgIIuAICCCAiAgT0xMzRMQTEUzEMxFEiEQIgAAAgoAIAuIACCKCTAwgoIgIIOAICCCgiAgi0wgIIOCICCLgiAAi4EQMIIKICCLgCAggoIgIE9KACCLgiAgi4IgAIKBECEiMIhFExBMTRIgTIRKjAKCAACLiAAgggogAM6KACCLgiAgi4IgAIoBMCACgiAgg4IgIIICICBPTgAAi4IgIAuCIACCARAgggIgIIICICACACAgi0zMiRMgRMUjIIjNIjEgIxAQzs8wEM9FEDBHziAQRkUQEEdNEBBGzRAwTo8wMM9NEBBHRRAwRs0QIEbNEDBHxzAwzkcwEE6NMDBOzRAQTscwMM7OICMiEEiJEjDEhyIgiISKjiAgQ4UgIEYEIBAKBjAwhkAgIAIAABBKBCAAz0kQEEaBECADAgAQCkIgMEZGIBCLBBAQRgAQAM9NEACKACAAAwAAEAZFMCMzEMxKMyCERSIwRMxGiEJIECAHARAgCkQQAE/IABACiAAASoogEIsGMBBGRAAQBogQAEdGAACLSSAQggYgEEYAAAADBiAQRkYAAIsFEAAHRAAQSoyEzxMQzIszEEzNEjEQIRAQR0QAEEcAECACCSAwRkYgEEoFEABHQAAgi0UQAEYAAAACAAAgA4YwEEZIEAACASAQC0QgAI+JAAADBCAAQ4oAIIYJECMjEIhGExDEzxMwTERKzEZFEAACBRAAAkQAEIqJIBCLBgAAAwAAEAZFICBHBBAgA4UQAIcGAACOxQAQBkQAEEZAECAGRiAwAkYAEIYJEBBHRRAQioyIzSIwxE8zMIzHMjEgMxAwxs8QMM9FMBBORjAgzk0QEEfNMBDHRRAQSscwEM9HEBBHRRAQTkUQMM5FMBBGxxAwx0cwEI7NMBDORRAQRkUQEEbPMCMSMEzNEjDMRRMwTMjLRIoEABALBBAARkQAAErJEBADBgAQRwEQEAJFIDBGABAAA4AAAAIAAABPyAAQRgAAEAIBEAAGQzAwAgQAAINAECBGRhAQSohITSIQREojEMyNEjEwIRAgRwgAAAuFIBAKgRAwAoggIIMKICCKiiAgT8kgAAMBICCHAhAgggkgMApFABAKShAQRoUAIM9KACACiiAgiwogIIZJMCMTMERPMzDMTzIwTMRGjEZFEBADBRAABkQQAE7IAABKCAAAQgYAIAJKIDBGARAAQooQAAKKACCPTRAQRgogAIuJEBCGAjAgRgUQAIsCECAGiCAASoiITyMQxEcjMEzNMhEgMAAAAgQAAEIAABAGRjAgigYgAAMKEABGRCAQiokQIEaKACCKACAQBgsgIAZEIBACRhAARogAII7JABCGSiAgiogQEIZKMCMSMMyPMjDMziIwzMzKyM5FMBBGTzAQRsUwEMqJEBBGRRAwR0cQEEZFMCDPRzAQR0UwEEZFEBBHiRAQRsUQEEfHMBBGRSAwRkUQEEZFEBBGRRAwyohMzRIwRM8zEMzNEiEwIRAAAgQgAEMEABAHRzAwQkYgAAMBEABGRQAQyokQAEYAECACAAAABgMwMAdEABBHQRAQRkUQAE/NEBAGRAAQRkUQEEZGICMyEIjNEhDEzzIwzMzKiEdIEAADARAgBkQgAI/IACCKigAAi4ogIIaLMDBGQAAAS4oQAIZGABBKySAQAoggEIuJECBKiSAwRgoAIIZKICCKigAQiojMTRIwzE8zMMzNEhMwMQAQBkQAAEZFEBBGRiAwQgIgAANFEBBCRQAgis0QEEaKACCLCgAgh4owEEZFEBCHAhAQRkEQAE7JEACKRiAAR4oQIIZGICMyEMxPMxBEzzIwzMSKjAZEEBAHRRAARkUQEEqJEACHBQAQRgIQIAJCICBGCBAgA4kgAIqGICCLTBAQRkoAEIOCECAGiiAwhkUgAIpGECAGgiAQi0zMzzIgzM8zMIzHMjEwIRAQz0UQMEdPEDBGRTAwTkUQEEZHEBBGzRAQy0sQEE5HMBBHRRAQRkUwMEZNMDBGxTAwzkUwEM/NEBBGRRAQR0UQEEbNICESMMzNEjDERTIwRITPTIOCIACKCAAgCgggIMqKIACCiiAgC4ggAIoBMCADiCAAA4ogIAqKICDHTiAgigIgIAqAACACCiAgigIgAIqIACACCAAgi0hMzSIwRMczMMxPMyIgICAgioogIAuIIACKCzAwA4ogIIuKACAKAiAgR0ggAIOIICALiCAAigkQMIqCIACKggAgAggAII/OICCKgiAgC4gAAIIKMCMzEERNMzDMRxIwRMzOiAoAAAAKiAAAAggAIIqKICCKiiAgCogAIIoKICCCAAAgg4oAIIqKACBLTAAgigogIIuIAACCCSAgAgIAIIuKACACiiAgS0zMzyIwzEczMMzFMxEgEiAACoogIAqIAACCCiAgi4IgAIoCACACCiAgy0oAIAICICCLiiAAgokwMAICACCLigAgAoogII/OACACiiAgi4oAAIoJMCMzMMzNExDEiSIwiMzKiEZFMBBGTRAQRs0QMItJEBBGRRAQx0UQEEZFICBHRzAQR0UQEEbFEDBPiRAwRkUQME/PMBDPRSAQRsUQEEdHEBBGxTAwiozMTTMwRM0zEMzFIjEQMiIQCAACIECCEhCIgItIgAYiIAiBIgBEQiICMCACAAQIAiCIiAIQhADPiEQEEgAAABMARIgCISAwEiBECiIgiAAiEABAisjMzzIwRI4zEMyKEiEwMEhEEiAAiRIAiEISIjAwIgCIhCIgCIQjAIiEzswEBCIABIgCAAQCAiMgIBIAiAYiAAAIAyAIhI7MBAYiIIiEAyCEAiIDMCMyMMRPMjDERRIgREjPSAIQBAASAEAAEiAAAItIBAYiAACEAwAECAIiIDACAASIAiAIhiMgiITOzAQKAiAAiCIACAYCIiAwIwCIhiIgCIYjIISEyoTMziIQREcyMEiFMxMwEEQEEiCIARMgBEAiAiAgAgCIhiIgAIYjAIAEyoQEBAIgiIQCIISCIiMwICIAgAYiAAAIAyAEBI6IBAYiAIAEAwAEAAIBICMyIMyJEiCIiSIwiMyLSEZHMBDHzxAQRs8QMI7JEBBGRRAQRkUQMEfPIBBGzzAQxkUwEE/NMDDPSRAwRs0QMM7PMBDPRiAQxs0wMEdHMBBPzTAwSozMiTMgRM8jEMiFIiEgIASEIwCAARMgAEAiITAwAgCEACIAQIACEIBEisgEiAIgCIojIIiKIiMwMgIAAEQCAECBEiCESI7MiEYiIIAKEyBEARIDMCESEMxJEhCERzIgREjPSAIgAIgDIEiAIhCIQE7IiIoiIIiKIyCIiiIjMDAiAAiAAyBAgAIQiIjKzAgEIgAAChMAREESIiAyIiCICiIgSAoiIIRIjshMzRIQTM8zMMzJEiEwMABEAhAAARMAREESIzAyIiAIiCIAQIEiIIhIjsgESAIgBIoSIAgKEiMwMRIAAEoiIIAJEhCEQI+IRAQSIIiIEyAEiiIDMCMyEMRPMxDEzxIgxESOziIgCIIiIECAIhCEAM9IiIQiEIiIEiBEQiIDMCACIERKIyCIiCIQhIBOiEQGEgCAABMARIgCAiAgIgBECCIgiAgCEIBAishMiRIgxM8jIIjPIjEgIRAQRk0QEMdNEDBGzjAwTkUQEEZFEBBGTRAwz0kwEMZFEBBHRRAwRk0wIEbNEDBHTTAwzkUwEI7NEBBGRRAQR8UQME7NICMSMETNEjDMRTIgTITKjBMgCAASIEgCIhAEAItIBAQiEIgIEwBEQAMBICADIEQIAyCICiIgBIhHSEQEIwAABBMAREADASAgAgAEAAIAQAACEABEiszMSTMgREkjIIiJIhEgMEQEEiAAgRMghEAjITAQEyAICCMgiIoiIASIR0wEBCMgCIgTIIRAIwEQICMAgIojAIgJEiAIiE9MBAgjIIQKIyCIiiIBECMiEERFMzCIijIgxIxOyCIAhAAiEEAAEhAAAItIBIkiIIQAEwBIQAMBICADAESIAwAAChIgBAhLTEAEEwCAiBMAREADASAgAgCEAiIgQAgCEIBEisyIzSMwSEczMMzNMjEgMAQEAwCAARMgAEACERAgAgAEACIAQAgCEIhEisgEiAMAiIgiIIiGAiMgIAIAAEoiAECJEiCERI7MgEQCEIgEEiBEAhIDMCESIIhNIiDETSIwREzPSEbNEDBHTzAwzs8wMErJMDBHTRAwz88wMM7FIDDORzAQz0UQEEZFEBBPSzAwzsUwME/PMBDORzAwTs0QMEfFMBBOxRAwiojISTIQRE8zEMzNEiEwIgAgi4oAIAuIAACCCTAwgoIgAIIKACACCCAgzsgAIAKKICCKiAAAggswMAIAACCKAAAgAgggIM7KICADiiAgC4ggAIoBMCMyEESJEhCEiSIgiIjKiAKAACCLiAAgAgogIE7IACCKggAgC4gAIIILMDCCgCAgg4gAIAIKICBOiiAgAoggIAuIACACCzAwgoogAIOIICAKAiAgyojEiRIQTM4jIIiJEiEwMgAAA4ogAAuIAACKCRAwggAgIIIIACACCCAgzogAIAOIICCKiAAAAosgMAIAACCKiAAgAgggIM6IICCDiiAgC4ogAIoBICIiMETNIxDMzzIwzMxKiIICIACCCAAgCggAAMqKIAACiiAgC4ogAIoBICACiCAgg4oAIIqCACBKjiAgigIgIAqIAACCAiAgigIAAIqCACACCgAgi0hIiTIgSI4jIIjOIjEgMRAwRs0QEM/PMDDPzjAwRs0QEEdHMDDOzzAwioswEM5HMBBHRRAQRkUwMM7PEDBPzzAwzkcwEM7PMBBGzRAQR8cwME7OICMiEMyJEhDERjIgSITKj';
    $data = base64_decode($data);
    $dirs = [[0, -1], [-1, 0], [1, 0], [0, 1]];

    $numbers = array_merge($goal[2], $goal[3]);

    $result = [];
    $encnum = encode($board, $numbers);
    while ($encnum != 0) {
        list($x, $y) = locationOf(0, $board);
        $i = ord($data[intval($encnum / 4)]) / pow(4, $encnum % 4) % 4;
        step($x, $y, $dirs[$i], $board, $result);
        $encnum = encode($board, $numbers);
    }

    return $result;
}

function encode($board, $numbers)
{
    $encnum = 0;
    $scale = 1;
    foreach (range(2, 3) as $r) {
        foreach (range(0, 3) as $c) {
            $n = $board[$r][$c];
            $i = array_search($n, $numbers);
            $encnum += $i * $scale;
            $scale *= count($numbers);
            array_splice($numbers, $i, 1);
        }
    }
    return $encnum;
}

function optimalSolverForSecondRow(&$board, $goal)
{
    $data = 'gFXVgFVVgn//teqqtdX1t92VVVdVtdXVtVVVtVVVvVbVon3/glffon//tdrqvdWXd11VdVX1v9WVfVV1f9VVf1VVtd////11qtVnr19vV3X9VVVV3dVnl1VVV11XX1VVWlVVt9WXv9X1llWlbXaVnXVlXVVVbVVfnZVfX11dn3VWaVVVtVVVv9WVVpVXWVVWVXVVXZVVl3VVVVVlrVZVVVVVVrVVVVVVtVWlVVdfb1VVVXWl1VVVXVVWVV2VVV1dlVVXXVVVtd1Vv9X9mpWtVVVV/VVVXdVVVdVffVVvV1VdV3VXWZVVtVd/v9VVllVdr1VvVXdVXVVdVVVtVVWdX31dXVVWVVVVt131v/31llV1b1VVXVZVV1VZVVVfXV1VXV1XV3leVVVfv1VVfdX1VZWValVVWbVVVVVVV3lfWlVuVlVdVVVVl1VV/93Vv939+Zevr3qarfWllZ1VV9/frdXfr91dl3V3W1XX9/n/q6+qq/6vqv/6+////f//+v/67f/+/fv/+v//+v/+r5a/q7+/6v//6///+u//+///+///////+///+///+v//r/f/vq6r+v//6+//+///+///+////f///f//+///+///t/X/qq+q+///+///+///+///+u//+///+///+///+////fX/q7+u+//6+///+///////+////f//+/v/+///+///lf3/+++q/v///f///////f//+////f///f//+v//+///tf/fq7+/+v//7///++//+///+////f////v/////////vfX/q7+q+///6///+/7//v//+//7/f//////+//7+///vvX/uv+q+///+///+///+///+////f//////+///+///v9/Vv9WXqrf9r/+trbWl/1VV93lf91Vu/11d/3V29bnfq/f/qq+q+u6rq+7ru6+/qv//quv6///+vvv/q///q7/+tfb/q6+qqqurq6uqq76/q6urq6urr6urr6q/q6u7q6urr7evq66rqq+rq6urq6+rqqurr6urrf+rr6v+q6urq6ur9/r/q6qqqqu7r6uru66rq/v7q+//u77rq+r/q7v7q6+v7bqqq6qqq6urr6ur+r6/quv7qqur+uurq6uqrquqqqvrfb2u/e+qu/ur7furr/u//fvr7f+r/vurq6v+qqurqqur97//qr+7q6v6r6vqu77/quv6qqv6rar6r7v+7fu7/fur97r+qqqqq6urrqurur6/quvrqqur/vurr6uvq6uur6v66br7q6uqqqurq6urq/7vqqu7qqur//urq6v+qqurq6urv/+//9+1Wrm/r/avr7r/9d/V17et9f/v93/1v3f/nref+qr+q7qq+6uqqv/q+q+qq/7/uu6rrf6rq+7/qu/7uq77r/Xqqr/6q6uqq6ur+6+/q/v/6ur/77urq+qrqqvrqqurn/r/+q6qqquqq6uqqqurq6urq6uvq7urq6qvq6u7q6urr77/qq6qquv7q6qvq6+r6vr/q7uvv/7/q+r/q7v7q/vvrvfuqq6qqquvq6uvq6//qqv7q6uqraurra+qqquqq6urVde/+76qqvqqu7uqr/u//buqrfuqre+rr6v6q6uqq6urtfdfq77+qqr/q+qvq/7/q6v6q6v6v6r6vfv+rfurr/urr7v/q66vqu+/q6v/q+7/qqv6q6uqveurr6urrqvuq6v6q7e/qq6qqquqq6qvq6/vqqurq6uqreurr6v+q6uqq6urv+r//er/V6mqqmVXqrapfpmqn+b/r/X/b/n/n/r/X/r/trqvqqqq+uuu6v//+q+v+vv+uq+q7q+q6qu6+quq+u+66pl3qr/vq6urq6uru6+vqquvqquq/eqqq6v+qqurq6urqruqu66rqq+6q6qrq6q7q+uqqquqvuurqqv+qqurqqur/7qrqqqqq7uqq6u/+6+rq7u7qqqq666rq6qu6qqrqqqrv+r6qqqqqqvrrququq6rqqr7q/r/q7r/q+ruq6r/q/ur1/q//uuq/+u77uur6uqrq/6///qv+/rvq6r/q6u7qruv3/r/uqrqq6uqqqv66q7uq/r7q+r/q+r/q/7/u7q7//uvv/r/qqqqqquqrqur+66rqqrvqqqv6/67q+r/q6r/q6rvv/r/uqqqqqurraur666rqurvq6uv+/q/q+r/qqr/q6uvv92qvdWq1f2rX129nVWl1f1WV33fqpWvqp1qurqmlrqqt/Wqv6+q+/+q////+/+v/fv//f/67v+76vvr+r/++vu/9/m6r/+677urv/ur6/uv/6uvv/ur/aqrr6uuqqurqqurr+2vr++rvfv7+/uv+/u//euqvfurvfurr6v+r6urq6ur9/m/76uq/fuq/au7r/qr6vv/6/vv676ru6r+q6vrq6uv1fmq+6uq7/ur7furvfuvvev//bur/quqq6uqqquqq6ur1rmq+uuq/f+r7fur7/uv7bur/auq+quqqquqqquqqquq2ruqur7qq6vur6v6677/rquqqquqrarqrquq7quq6qurq7qqqquqqqurrqurq76vq6vrqquq+quqqquqqquqqququrmqq6uqqqurrquru67vqqurqquq/aurqqu6qquqqqurfV3VfdW9Wf3//1VvXddX312/13Xf/f1/9d2t/122lrmq9/v/uqvq++v+q//++7//+/u7+u/7///6rf/////+++/+9/nfq+/6q6vqq6v66///qqurq6vqr6u6raqu67urruurlff3u67+qvv/q6v+q7r/ruuqq6v6v6v6/av6/fur//urt/r/q6q6qqvurquru67+qvrrq6r/6/7/q/7/+7v7q/ur9Z+q676qq6vqr6v6++7+quuqq6uqrarqrqvqreuqvaur9/2/r7vqq6vq/au6q/r/qqurrav6rarqr+v6veur6rur9f+v+6+6qruuvau6q/r/rqv6rav7raqqrruqrruqrbuq3bm6+++q//uq//uqq/+//qv6//urvruqrquqqquqq6uqmfm6++uq6qur/fuqv/vv6qu6vuuqvauqqquqqquqqquqvd/V/d//X5nfr21fr3b1f11Vl/nfv13+n13+d1n+V53fv7v/qq+q+v+7uv/7++////v/+//6/f/r+/v//vv/+//6v5Xfq//7qqurq6uru7+/quv/qqur/eurrquuqquqq6vqr7fru66/qqvvq6qvq6rvquuqqqur/furraurr6uqq6v6//r/uqqqq6urrqu66q6rq7v7q6qvu/r/q6r/q7r/q6r/vrmuqquqqqurrquru66/qqvrqqur6quqqquqqquqq6uqlbm6++/qvvur/furq/6/76vq/auq/uurqquuqquqq6v6vbr+q+qqqquqrauquq7/quuqqquqrquq7quurquqr6v6r/7+u6uqqqvqr6uq667/quuqr6uqrauqrruqrauurav6ta+/u7/qqquqr6v6++7/qqurq6v6rav6r6v+/vurv/ur/dr6/+r6X6mvqm1fqrWlfllVm3lfqlVual1dX3V3X7lWv7r/+qvq+v++qv//+r//+vv/+u/6/v//+vv/+v//+vv+qlV/qv//q6urq6urq7+vqqurqqur/burq6u+qqurqqurrrevu66rqq+rq6urq6q/q6uqqqurvfurr6v6q6urqqur/rr/uqqqq6urr+v76q+rq/v/qrrv6/6/q6r/67v7q7r/upmqur+qqqurqqurq6qvquvrqquq/qurqqu6qquqq6uqlrm6++v6/v+r7fur7/u/7buq6vur/vurqqv6qqurqqur+r+/u7/6q6v6q6v6677/quu6qqv6rav6rrv6//+r7vurv/m+q6vqqqurr6ur+67/quu7qquq/eurq6urqquqqquuv7m7uv+qqqurr6ur+67/qqurqquq/burqquuq6uqqquqIKqrBKirhKqrIaqrq1VVolXVolXVrlVVqlXVqlXVot9XgIqrBKqICKirgairo1XVKlXVqlVVrlXV+lXVolXVIl9fpaqrAagrkYALEQoDA33/gl31glVVLlVVilX3AlXVAv//oFXVK3VVC9f/tXa6tVelddXXtV9VtdX1tVV1td9Xv+v2ol/Vol3VAl//v/X6t1bdtdeVtVdVtdX1tVd1dfVVv+bVqlVVolX1Alf/tVVltdf1tVVVdV1ftVWXt9VdtVmX9Vlf/1XV7lVVvn/Vtdm1tVW1tVWXtdWVtVX1tVVVdX9Wvd7VqlXVqlXVil//tdXqdddVtV19dVV/tVW3dVW1tVWXv9X3qlVVIlXVAl//tdnmtdfVdd1ftVVVtd31td/3tX1Xv9Xbql9fIn9fAt//v/X1v+b1t1lWdX9Wv9W3v9XZddXVtd9XFaqrVairVYqrASiLi1XVglXVClXVvlXVilXVilXVCl/fVairhaqARairJKqrsFVVqlXVolXV7lXVqlVVqlVVot11ZYorhaqrBqirBair43XXol9fqlX//n1Vonf/ql/3qv//MFXVr1XVs3//teuqtX+/tdn/VXVltV/9tf2/tfqft+r6iFXVolXVql//tfmutdWVtVX1dV39tVW1tVV1tVV1v9nVqlVVqlVVqtX/VZWpd1VVVVVVtVVVtdVVtdVVtVVV/1XV/1XV+lXV/n/Vter1tVX1tVWVVVW1VVd1V1VVXXdVv9XVqlXVqlVVql//tduqtXVVtVWVdVV1tVW1tXX1t1W9v9X1qlVdqtXVql3/vfX5tXV1ddVVf1VdvXXV/1V3tXV1v9XViv//ov//qt3///X9veXVtVVVv/XVv9a/vdXVv9X1v/VdA3VVAFXVAP//tfmqtdf1tVWXtV+VtdX3tdV1td9Xv95XA1f/41X/71//v9f1tdX1ddf1tfX3f9f9t/X3t/X9v73/tf6qv9d3q/7vq/3/rZ+l7//9/e2t6b257/+v7e25662ptd31/1Wf7v3/raup7futt72v7/3vtfuvrbmvrb29rqr6df/Vv3W/tu29re2/r7//79397fXlnd/9tf/37f/d6v39tf//vfX//b2t9/3tb9/9733f7/3/b3/97/3/r/3/7/39td3/v9W3qZ3/rbq9rd/Vn32/b13/d33t/f9X/+396r39td31v/X36/1/tfqurfdVr33///3/rf//t/3/r/35rt3/tf/bv3Xfrf3/t+3tr9/1733/7/3/t/3/+/3/v/3/7v3/f/q6v+q1/v396a29qb91r/3/6u392p3/6f3/6v3/+/3/AlXVgnXVAn//tfqltd+Vt/391f3/tXW1td2XtfX1v/n5An/fqnV1qlXfv/X6vd/9tdWVtdf9v9fX/9V3v/fVtXZ19fn6v/X/rb2qqa2pqbqdr///r3/tb9/96///r///r///tf+Vv9eV+r7/r/3+77+9rb7/rf799f+vrf7/rb3/q7+vtfeXv/X/qv39re7/qff/715dra+lvV+trf93ra/d6a6911//3dX9r/3lrf7u7aept66/7u76rfr/+/7/q/3/q/3/tVX1vfWVr9//vf3v9V2lr+2//b2q9a2q7a3q763urq2u9XV1tdW/r/929f7/redVr/7/7a2u/f+u9e2n/f+uub+utf//v9f/qv+tve6vraf1/+7/ra2q/W297f3/r+3/7q3ever6v9X1qv3/ra6uqa/lu77/7q6qta3q6q1r767+ra39gn9Vgn9VAt//v/bvv+r/t9n/t39VtV91tV9VtX9Vtf/Viv//ovX9qt/f/7v2ver/teX/v/71vd+Xv9/Xv/3fv712v7pav7WVvu39qa2tqaqpr62tqun/mbq/6blfr62/v+n/v+r/v/r/qq6qqa7vqq/d677/u/3+73/9r/2fr/39r63+vd//v/X/qr2q7+39r7eu6Z+qr/7/b/u/7/7/7/797/7/v///v///qq2qru7urvb+r+7/qf/+r///re7/r/79rb//td+fvd+7mb297/29b/79r/+9bW+lXW/lvf/nve/9qr+9df/Vv99Vqfr/7/26b/7/r/7/7f/lvf/3/d/3re/9q/+t9f/f9f93r63+763ur/f/r679r/+lrd+tr//1/e92r7/3vf/6v7/+qv3pr+3ur/f97+79qq61qe+tvf/3r//9va/97lX//1X/////tVqqtdWqt/2qdX22v9n/v9n/v/r/v+r//n3//lX/ulX/vdWrvdWqtdWqdfW6/+r/v+r/v/n/v/n/tfmqv/W1ft2t3V2ubV+pb/2v3d25qqqqqbmqq626qq2qtXWqv9Wq7t26XW2v7d+tb/2/3V2q6q6q6u1/qq39qq79tf2qv3Wqmv2qVe2qrW//r/6tvV/lqZ+pqb+mqq+qqq+ptd3//dX/9X2qfd2t7V/t321/fe3/b7+q773v772uq62qv+r/v/r/mqmpaq2qqp6pab2vn/7ur/q/rvr/rr7/r+7vv+r/v/r/qqqq+q1/qpdqqr+qr/7/7/7/7///7/2/b/3/v9r/v/r/qqqtru7+qq+p772vr+76b/r/777/7/7/r/3/v/r/v/X/qr2puq69qa+pr77vr76+b/6+7/7/767/r7r/ilXVqlXVgl//tVuqtXVXt121dfX/tV31tXWqtX2mv9mqgnf/olXdqlX3f/X1tfVVtXW1dfd3f/e9f/WqvfWqvbWqtd/7v/f/rb3/7a2vbb9Xr/397e3/7b+77/+q/+2qr+2qtXeVf/d36u1fvf9/9f93r/3//a3+/f+/Xf+7/f29WZ3qtf9dv3X/qv2/r+3/qf9/7/79te92rd/XvX/n7e+uuV+pd/n///X/9b3v9e1q7edWr/7/vu36r/+/r/7/r///n+27tX3Vv/W1qv2/3f2/vX9Xr/2/7//q7f+u9+9r7+3uqq3ttX2qvfWqr+2q/f2v/V+lv/+7/e/v6b+q6q2qqq6qqq2qtf2uv9Wqqv2qXe2+r1/2b63/r136rq6qrv2qqq2qqq2qv9nqv9Xqqr2rea2qq19lr+3/rq26uq2qqq2qr+2qrr2qqlVVonXVCt/1tfd/9ff1d91ftf/19d3X9d//9V+Xv/33it33olVVqt339/f/3d39tZX3v/X39/+3t/3/3fV3v/X39fmvt///r62tr636rZ/Vr/3/r+3/r739r+n3//3/u+3/1f3/9fW/r617va7pra/l7/7/r62qta2+r+3u7+3/ua3/tf/1v7Xfqu357+36r/f/7e39+q/lrZ/9va/V7e9W9f/3t///v/X/qr36uu7trq/q767/r+6/b/r7777/r/3/7/3/tf3bvfWrr62/b626r1/V763/r+2quq2qqr3qv63rvq1ftf/Xv/X3qr3vt636r6dWr+7/v+3qv63+v/3/r+3/rv3v93/ftf/fr63/ve3+redW7/7/uu3uv////+2ur+/7uv+qv+r6v+X16v2/vq27q+dXr/3/v62q6/+vvu2v7+2+r63uiv9fov9fAt/fv7///+b1f5lWv55W/5X7/5XZ9d/X9d//Cl1folVVqtXft7f/3en69aX2v7X5t+r+97n6//X/3b////3/t///r72tr+3uraupr72uv+35r6q5r7mqv+35v+263+n61bb6r63tva6vqa+t6/7/qq2q+a+uqu2/7a39r63qf5/Vv7r6qq2+7+35b/r/6Z59qq6laZ+prb937e+t7775v+r/v6rvqq2tqq6tqq/pr71vqu3/b//6773/r/7/773+/9m6tfq6r62p6a26qV2p663/qv2qqq6qqu1rqq3uqq3t/+r6tfr6r62u6q2/aadV7/7/qq3+6b+q6q267/29r73q9//3/7X/r/2/v+29ra+1r+7/r62qf229++3v7+3/r63+37/f///7r63vr62ura/V7/7/qq6qra2qr63+/+3/r63/gK69QAWhAqy9BaCtDqCuqqqqqqqrp72r/6r+oqqrKqqrAKCuEQQdEAShBYqhAKCAKqiqIqirA7irD+qvAqj7IqirBaq9VQQhEow9FSANAqGuAqiqiKirg7GrD6j/BqirAqirCaCVFACgVKEAVCksBCEsoqgLUYqrIaCL86iKIaqrESqLK6r/BqiqAKi7QgA7C1dVi1XVC1XVr1VVClXVA1XVC39foqqrBKioBIorEYCLC1VVglVfCtXVrlXVqlXVAl/VAl9fVeqro7yrE+iLVagL/1XV/1XVDlXVDlXVilV/ClV3Al9X/qvqD6r/A6iqA6iKKlXVCl3VClVXqlXV+lXVjlXVDn//IqqrKqirAKqrQqCrC1XVilXVClXVPlXVClXVClXVil9fIqqrBqiriCorUQArC39fAl9fAlVXDn/dCl9fClVVAlVVUay9BYWhVAwNhakdjKmgiqiqkoqrJ7yLP6j+EqqrkiqrFa29FaClEaGshaqtnqquiqqqqqioRP2rPK7+rK2rqKyrRaC9FSAuVCowECAMEKCshqq6iqqrB/2rz6r+CqqrCqqrlZalVZm1WqCuBqKuBiquBerqhaqrVP2rJ6v+CayrCaqrEQoDBA8AD6qqpqiro1/Vo1XV71VV8FXVslXV81XVo39fqiqrqqqLCqirhaqrsFX9qlV1qlVV/lfVql3VqlXVqlVXdfirX/2rR/2rpf2r/1VV/lXV+lXV7lXVqlX1qlVdqnVV/yv6v6r+Dqr6+6r6olXVqlXVqlVVqlXVq1XV/lXV/n/9qqqrKqqjCq+rJaqroFXVqldVqlXV/lXVqlXVqlXVqn9fqqqrCqqriqqrJairsH9fqlVfql9V/n//qt9fqlVVqtVVFZWmlWBVFpWlBVJFVKGsVqiqVaqrVfyrVaj+VaqrVaqrFVWVFWFtEGGVFUllFKCuRaiqFaqjVf2rB67+Za2rVa6rFVVVFWFdFWFlFWBtFAMAVYGqVaKrVeGr16H/VYOzVYCjVZSlVYC1VaGtlKiAFKCuFqiqiaKrFP0rR6r+iaKriaKrVQgDBQEAVaC7goMrI1XVAFXVo1VVMFXVIlXVs1f1g///VaqrRSoAVSILqaKro13VglXVglVV/lXVglXVClXVitffVfirVb2rVfyrFfKr/1Xd/lX//lVV/l1Vql/VqlVVot9XVav6x6r+V6P6N6r6olXVqlXVqlVVqlXVK1Xd/lX9/v//aaqrCqqLVaKrqqKro9XdgtXVqldV+tX/qtfdKlXVqt//VaqrBa6rlaKrpaKro93/gtX3gt9V/t//qtf/gt//qt//0AsDBAgAdwADgQsDi1XVANXVA1VX/1XVAFXVA9XVA39fswj/v+HwuigwBPjz41XVA1fV8NXV/1XVA1VV/1XV819fUQj/hC/zNeMztSILo1X/A1VVw1V1/1dVAFf/A1f/A/3fAFXV4lXVr13ftdn/tdXuvffV13/91Vf1tXeZtf/1v+/7AF3VA9XVA9//tXauvVeV9fe1vff9tfW/tdV1tfV3/7qtMFXV71VdM9X/3dfqtfe/tf/1f3dftV9fvVdVvXdV/bee81XV/1X1/3/dtVe5dde3vfeVV/f/Vf//t/X/t/f3v/b3AFXVAFXVANX/9ffXtfV1tXedtff/tfX3tfW/tff/v/aqAFXVI9VVA9//tfaptfeXdb+Vv/f/dfeXdbV3tXWVv7VXAH9fL39fA9//v/b6v7Xpvb9lt/b/v7q6v7XqtbpmtbWVEKqrBqiLCAqjAQAjC39Vil9VAlVVPlXVilXVClXVAtVfEqgLBAEgCqiLJKiro39Von9VolfV/lX1qlVVolXVotffRSirCKqrVaCrhQKrI9X/AtVVAl9V/lddolV/Ktf/Ktd9AH9VI19VA9//v7blv7Xlv9dVvfr/dfV/tfXrtXf/vbX3iH1Von9VCt/9t/b1t9f/vff/tf/VtV+Vtd9Vtf+VtX93CFVVot9VAt//t3bqt3p39fe1v/b/tXV1tffVtXedv7fd/1X1/1X//l33tfWvtV+VvXW193W//fX9/XX9//V3v/r9ilXVotXVKlV3ddXvdX9VvddV/9X/tV239VW1tXWXv/WqiFXVolXVolX/9ff69f9XtffXtVf1tfX1td/39fVXv/f3CtVfItVfAt//tba6tX91tbf1v/b/v/W3v/X2tff1v/X/b74rF/gLR/CrJfEL81X//lX//lX3vn9Vil9VCl9VCn9V0+gL/72g3/wKBb6r81X//nX/71X//n9Xiv9Vol9Vol9XVfirVb0rVbArRf0r81X//lXVvlXV/t//itd/Ktf/At/d/1X//1X//9f/tfeqtVW6dfWVvfW/v7bqv7Zpv7d3v7b1/1X//tX//l//vXaqvXWmtdeqvde9v9n/v/b/v/v/v/b/71XVutX37tX3dfW293f/tff9v/VZt9//Vdf/9df/v/X/739V/39//t//v7Wqv9bvv/b7vX9/tX/2t3t9v/53tf91in9Von9Vqv/3v7Z1v/b/v9b/tf99tV+9dXeVtX+Vtf+2Cl9Vol9VAt/dv7rfv/b/ddX/tX//9f9X9f9VdX9dtX/fKn9Vqn9Xgt//v/r+v/X/tf//v///tX/q9b919f/31b9VP6rq/6v+/6P6/yv6qlXVql3VilVfKlXVqlX//lX//n//8qvqyqrg76v+/6uqqnVVqlXVqtXdqnX1qlX/ulX/rt3//6qq/6qq76Lqy6P6olX/glXVqlVVqlfVqlf/7lX//v3/IFXVqlXVglf/tXa5dXVXvXfVd/X/VXX1tXWqtfWWf72qqlXVqlXVql//tXb6v3fVtXdVtfV/tXX1tXWqtXeqv/f6ql9VqvV1qtf/f7Vqf/V/tff1v/XfvXe1tXelv3elv/XqqlX3qlXVqtf/tXW1tXWVtfe9t/W/dfX3f/b/t/f/v/n/qlX/qlX/qlX/dXWqtXWqvXeqd/W3v/b/v/b/v/r7v/r//1X//tX//l3/dfWqtdeqtfemv/X/v/b/v/f/v/r/v/r//3//+n9//t//v/qqv9a6tf91v/f/v/b/v/b/tff/v/b/qqqrKqqraoqrIgoLq1XVgt1VCtX1vlXditXVitXVKn9foqqrqoqAqqirqqqrq1VVqtVVqlXV/lX9qtVVqtVVqtXfqairqaqrKqKLpQKroNXdAlVVil9V/tf/KtX3qlX9qtdfIFXVL1XVANXX1f//9fX9vdddt/f/1ffvtXf/tfebv7X/iNXVot9VCtf1tfW/tZ9VfbdVv/b11fW/1fV3tXdXf/XVKl9Vot99ot//v7b2v/v/tf//t/f/tZ/adZ9Vt3dVvVfX71Xf+tX//tX/tf269fe7tfWVv/f/v/v/v/r/v/f/v/X/KtXVqlVVgt//tf7etfdXtf+dv/f/tfe79fe6tfW3v/W6qtXVqtXVCtX9/ff3tbXXtfe9v/b/9bf1dXeqtfeqv/aqqn9fqn9fqvf/v/b6v/XWtXf5v/f/vfa7v/W6tfW7t7XqoqqriqiraoqroQori/9fit9fAt93vv/fit9fitVVCtVVoioriqqrqqqrqaqro39fqvVfot/f/n//qv9fotVVotVVpairqaqrKSIrpYKro9VdglVVKl9V/tffqtVXqlf1qtVVAP9fI99fA91f//////X9v19Vv/f///e/v/X/9ffX9ff/itVfot9fCtdVf7X/t59Vfbf1v/r9/5W6/7XWtfX19bf/Cv9Vov9/gt9/v7r6v7r/v9f/v3Zff5+afZ9VtXfV9bVX/////v///t3/v/26/5a6f7eav+r/v7rqv7r/v/b/v/b/qv9fqv9fqtVX//X/37XV9Zf5v6r3v7a6/7a69/WW9bWqqtVdqtVdqtdf/bfXtff/tb91v/f//f+b/7X3dXfX37f/it1Vov9fqtff17f//bX99Z9Vv/r/17eqtbf/9bX9tff/FITVFLX1QBWFFYAwFLD0M4Swiq6pBpC9BfRvP6P5u6q9ABXAVHX1VLX1FYC6FYCRFYSwRICBUAGhAcQEBAHBKooBFYDqVYH1UAGFFYWwVLX0EwS1GIStBpWhBfRvP4/NSIqhEYCRFbD0UBW1VIE2FIH0NYC1lAoNBIS9VQQvNa8yuo6tEI3AN0S1FE31FYS1EbH1VIWwQqGolIWsFOEgc6H8KqqMiqCtQgUBQAANlQYNlCHAgqiqAqirB6i7Dqi+QqirMqi7BWy9BJChBgUNBYohDEGsU/g7A+Cro6iLz6ivIqqrAiqrB+2/VTRvAgUvBYavgKFzu6j646jr/6jqDvyqA+irAqCrD6y9M4cBM6w9H4+9HKHMCqiqoqirJqyrPqqvD6j6I6jqKqr9SIqhEQotaoCtKqqsAqi7IqqrIqgrD6j6IqirYqqrVbXVFbX1UIUVFYC1FYH1f4y1JoqtRIW9RcUvN6/yP669VbXVVbX1VYX1FYC6FLD2cIC6KqmulZmsVepv9an/Pq+vFYGAVYC0UYB1VUCEERW0UBUwGqCqEGEtUKBvP+C9SqqtFYT1VYC1ULX0FICEFID2HIC6iaioVdmtBehvT6v/LqCtPICaP4C1VRWAMIC2EIWwEIHwSqjuBlCuBqBbz2z+CqqeKKr9KqrtEKGsiYCtiKCqiqqqKqr6VP6rruv/iu6rOq77RV25FfqtVJEsBVIt9aGuR/2q3/2rRP2rv6v+LK6qCqqrlP1/FerXEOBvXepvBfBf76r+z6r+/Kv6/6/++v2rVv2r/K/5/6+t/6HtP6/tDqD+i6qqiqqrZP6rPq6q/6qqz6r6PKq5P6qtGqCuSoqtKaquj6qqKqqrRP2rP6v+CqqrqqqrFbX0FYCRVLX1FYCFVLX0Fb/1VaqtVYSuVYQvVe/yaq/9UQXVVbT0VYX1FYCxVLX0UL/wVaCqFZG5V+BvPaP/Ka+5FYV1VYVVUYV1VUX1UYHVUIC3FaqtVS25V7k/PY3xbo7hVbX1VYX1VbX1FYGwFYWwf4AwKqqqFKAuFeCvPaP9PaKuNb/wVb/1VU/Vc4W1f4C5fIC1GKqsnFatHNlR/K/mPKqtRCoBVSBVVSoNKqC9FaqohIGiiCILWMIrxgDwCuIAyqLzBZyuVbCuVZGuFbC5FUm4VPGCSv2rZvGrv6H+qqOrqqKrVbV/daCXF6F/EaCvFfVf/KP8rqP6/KH6P7H+u/27lP2r/6/+3+D+/a++/6+t1a74hIGqqqKrbvGrv6GvP6Cuv6P6eq/9aqDtFK/tMaq5v7mohAMiiKKrl/Grv6H+iKKrv6KrFVC1VVCQVRWVEIS5EICxEYX0VVXFBVRlVVVXFVXVLpqVVV1VVVCVVVWVVYG1XFBUUEG1VGFVVWGVVVBdFWFdL1pdUIXVVYVVVYWVVUVEVQHVUIDwGlFUFVVkFWFV31FdmpuVVFCUVYCxVVWVUYW1UIW1VIC1VWpdUFGtFFFVFK9VKaqtVESVVUH1VYV1UUFVVA8BULPxVGFQFZSuVFFRVKB2maD8VlVVVUBVVWFdWFXVFYWoVaiqVSACFA4yVQjwFQEDdYIyVESVFVAVFVVdVFltFIGuVfGiVfILVf4Ldav+aQqrVQKrVFRXVWFVFVVXVFFXFMEfRoH81QL7VaH6VPP+Vf2rVf2rF5VVFV2VMGGlH2ClFYX+VaiilQIrVPKrS6OrJoDuVaH6KZqVGonVIKqdJqCtKYPMlaiiaYADVf2jdwv+VYCrKQurFSA9RAEBEaANEZC9AKCIoqiqQAgD1/wD/8j/0AgDwAgDFC0dVQAFECAARaGtDSDOhKqoAAgARM0zzAzwhMgAxPjzRKD9EaD9Fa39EQDtEAUABCCqCgEzV/AAvwH/PgADPwAzElBGEAAVEGFQAKDdEKDshogiFSIDVP07xgj/ReID1QvzkwoDhAIACiACgqK7o1dVondVgNXVwFXXoFXVwFXVg9VfEAgDBAEABCDzBggDo19VAFX1A9dVPFXVAFXVg9XVA/dXwcgz38IwX8A/Rv0zz9XV/FX1/1XV8NX1AFdX89d/A/9V0Ar8xCDwPwAwxgP8gFXVAlXVgFfVAFXXw1X1/FXV/9//kQgPhAEAqiAjgAIDo1XVAFXVA9XV89VXAtXVAFXVAH9f0wgzBAMwD8DzxYOzo9VfA9XfA1dV8N//AN9fANVV49VVAZy9BeyhVNUNBVK99IUMV7iq17irF7yL/6j/UiirUioLVe19FdAFVdGABfChHaCu1/yq9/2gRP0rPK7+hK2rpKqrUfw9ReKtVdE9VVEuHIMAd/Gq3/0jlPALz6H8LgAjCAADVVUFVaG1VUWsVGEtFGEsRv2CVf2jVP2rR6H+CQKrCYCrUfgDRz0AV/AqBDGz/1f/z1X/z9ff8H9VIl9V419VI19V9/Cr3/6A//ALFfyr/1VVv9XX/tdd/l9Vgl1VilVVqldVRfgrX/0AV/0LRf2Dz399/n9//9XV/l3fCl1VAt9VgtVXz6v6w6r+vyDs86P6gn9VildVKlVVilXfqlXV/lXX/tX/AiirBKKACAALBqCrgF9VilVVAlVV/lX1glXVqlXVitVfKqqLqiogiCILJYCro19VglVVgt9V/tX/gtVfglXVgtVV9ex/BcW/e/VvXf9/XPED/qj6/6v6/6v6/6v+V/irVvirf62/X+D3deB31fCvFeH7/6vq/6vu/6v6/K3+762rr62r1+/vVav/ff//faF/HPUDy6P676Pq/6P6/qH8/7EjOvwDVdVXVeFXVcEfFPlfFPFT/6PC/6P6/6P6X6H6V/wrVf2D/4v+/4vw/6P+P4P+qlfVgFXVqtXVgNXXP1X//1X//////qv6/yrC/6Pq/6v6oNVVqtV9qtdVqlfVK1X//l///td//6jq/ivg/6Hq96P6glXXitXVqlXVqtX/qt/VvtXV/t9X/6v6/6/+/rM8/6P6iFX/qtf/qtX3il9Vq393/l///n9VbfirWv0IV/ALFfArz1X//lX//tXV/l9Vil9Vgl9VKl9VY+CrGoKrhOArVfyr/9/f/tff/t9V/l/3qv9VClVVqt9Vz6+t/4/+/yz9N5/9/6Hwqqiqoqqrprirrqqvvqqq/6v6/6++/6r2/6Dy/6/p/q+qiqqqqqqqav6rrqqvv6qq/6uq/a/9P6+p/6/J/w/qP6v6BKGqioKrluKrLqKu6qOq76Pq15Xp3a31/6H536/q9K/ohYiCqqKjlPGrqqGr+4qq/4P6kogDhIGgCoCjhKKio9dVs9XVq9fVstX/ItXVotXVqt9fqqqrqqoIqiKrpYKro99VglV1AtdV+tXfotVVKldVqtVdofirL+6rGvArpvCjP9X/7tX//l3V/t93Kl9VqldXKt9VqqqqKqquiqKqqaKqoNXVgtXVqt9VqtX/6tX/qlX/qv//q6qqqqq+Cqvqr6KqotXVqtXVqtfVqtX/qtX/qlX/qt///qvq/6rgv6Pq+6P6oN9fItVfql9Vqt//qtff/tX9/tX/iqq9qoqhqioNqqq9qqqsqqiqQqqrpvwr/6j+kqqrkqqrqqr9qiqtqqCtqqqtqqquiqqqiqiqRP2r767+qq2rpKqrqqq9qqqtqio5qoquqioMhKCqKqKrlv2rr6D+rqKrqoCjhpqllhqlqqmspqqtqqqshggCFYqDVP2r56D6SYKrioqrkwoDhAEACiCrhqK7o99fo/dfg/9f8P//It9f49dVgNVVEqirBKqAiIALBSCro/9Vgv9fAt9f/tf/it9fAtVVitVVhfgrG/2rWv0rVf0j/////t/f/v/f/v9/Ct9dqtdVAn9V/qv6+qq+r6L6+6P6ot9fitVfCv9Vit//qtf//tX//tX/oqqrqqqL6qKrqYKro9VVgtVVql9V/tX/qtffqtVVqtddqiqrqqqjqqKrpaKroNVVgtVdAv9V/tX/qtVVqtVVqtVVAALAAAJVAALVqiLQoqpUAILQAALAFIClFYS1FcGR/Y/+AALVAALVAAJVKgLQAijRAALQAALRFUEwFYSVVYHFf7/6qiLAqgLUqgLVKgLVgqpVAILVAALVFAW1FQU1VcWT/b/6oKrRIqpUAoLVKqrQqqrQqoLRqgLAFIC1FYC1FcWz/7//CoLAAILVACLVioLVAipVAqLQAqrRFIW0FEGzEdGU/7/6AALVAALVAALVKgLQgioQAILVAALVFVW1FUVFFQWV/7/FFISAFYC1ELU1FYAxFIG0FIQFhEQNhASNhQQP/y8xhirNEIXVFUS1FLX1FYC1EIHRFR/0RIQtBMSvlz+vBwwyKoquEYTTFdXxVBXXVYC3VIHHEYSFxA6tD4+wB4f3My/+Ko+Pf7/KPb/6V7/KP7H1f7/6fw/6KioNKoquKoqPxI+9P68OqgJVqgJVqgLVqgLEAqrQAILRAALAFYClFYC1VcW31b//qgJVqghVqgLVqArQIqhQgorQAArcFbG1FUD1VYBV37//qgLVqgrVqgpFqgIBgqjVAArFAArVVRW0FRW0VQWXf7/6IKrVKqjVIqpVqqrAqqrQqoLQqgrQEIG2FUC1FcGXN730gILAAIrUCoLVqorQAqjQgqjQiqoUFEC2FICRFYS3/7/6AAIAAAoQAALVqgrUIqrVAALVAAoMMIUwEISwUACw/7DOFYSaFYC2UbU1FIC0FIG0EMEAhZipmlGumqFbNqOrmqCtFYX1FbD1UXX1FYC6FXCxMIGwRaCuVeHvV+OvX93/KpqtVYXfVYX/1RR1FYC3FNDwEIXMyqD9P5Ot/+D/P/z/+qq/1b/61b/6X73AP7/1f7/6cAP6aqqpSpqua+qf/6C9P+/9KqpUAqrRAqpVqqLAqqpVqgJVqgLfFbW2VbX1VcXTf7V3gopVoqhVqqjVqqrQqqhVqgJVqgrfFbW6VXX1VdVVfbffqqLVqqrUqqpVqqrVqqDVqgLVqgLAVYW6VYHVUYW1f7//qqpVqqjVqqpVoqrUqqrVqgLVqgLAFYW2VUW0VYUT1Y/2qgJVqgBVqgJVqqLRgqjQgKrQAqrUFUC2FYC1VYW39b/6qgLTqgrfqgLXqgIVCqjAAALQgALAc4Cqf4C6VYC7/7/+FbW6VbW2UbW2FYGwFYG6f4C6KlmuKmqpGbJXP6mpqqqpFbX1VbX1VbX1VYWwFUG3P4C2KqmvFPmvF/W/P+/9PJquVdXXVfX31YXXVYW/VYSfVYCXP6r+96++1/v/P///N6r/f7Vzf7U3V7V31b/61Y36/7D1IKrtM5rukfav8K/+3+/+gILVgILQIoLVqgLQgqrRAqrUgqoVFVS1FYWXVYX1f7/5IoLVqoDRqorVqqLQgqjUoqrVoqrVFVG1VUDVVcFVf7/WqoLVqopVqqLVqgrVIqjVAqrViqrUVVF0VQVVVYXV37/5gKrUgqjRKorVqqrVqqrVqqrVqqrUUEW1VEGVVIW1f7/6AKrVIqjVAqrVqqLVqohVqqJVqqrfFbW6VLXxVIV3/7XfoKrUqqrVqqrVqqrVqqrPqgLfqgLPUL+5FYwwVUEA/48MFES1VUC0VXV1VEF1FLW6VL8xVaoMVYYJVbGjfwe4mQqpVHR1VYGVVbX1VIGXVLX1fbP0VQKu1fGuXPGnVe+uGaPuVcX/VYXXVYX3VYX1VcVfUIHx3Q88f0e9ffH/P8P/fqPefb/6/7/a/7/6f7f0f7XHfw8DaoAAKoPhagF3f4D8PQP9AAIAAALAAALVqgIVAqrAAAIAAAIFEEB1EEBUVEBFc7/1AALVAADVAALVqgIFAqgAAAIAAALVVVAFdVBVVYBVf4N+qgJVqgpVqgLVqgpVAqjVAAIQAILcVQFWVQHVVVFV1U/fAKrAAqjAAqrVoqpVqqoVqgJVqgLAUIWqUIV1UIW3PwXVAgLAAAABAALVqgJVAooFAqIAAKLVURGRUUVEUICRcED1AALQACDVAALVqoLVAojEgKLRIqrUUUW1UUVFVISV/7/1UEBVX4A1VXVVUIU1cERBVQU1VWFUXFREWFFRfEJUFRFUcFxAX4BRVXf1cYVVcAB0VYVAVVFZVFRdVEVVVWBWaVllVEDFX0BVVUXVUYXUUUFFUIDFVVlUHVWlHV3VVGFSZZlXPH9aP7BWf0/ac7/1cIDacID2GkJcalatJlpVFV3U359dFYQQFUSFULVUFYC1FIUEEdWAVZytAAAdAQAPFCDMJGoNVbWVVXWVVUQxFUEFFIAEU/AAFG2qRVEBdSBfFSDNJaoxUbUQVUA1VURVVUQ0VTVVcPC7VdEhEA0NEfkMfwExEAUBVUUFVYGAVUG0VIU1VEE0UIAwVVmhVFCpVaB/EQP9KoD9FUAAVYWAVYUBFcEAVUWgUISAdFGQDBAACFBBEipUKioNVGytVfClVW0NldSp1SGolPGqd/EKWw6ghgjAioIAqqIjUFwBEHAVFVENVVGBEAAARPGqVMEAVAgDDgjwCAADxAgDRPFOWiADFSF8XaF/AiBPj4HAPADwzAHw/AH8xMEDRP3DMiDhFSr1UAENO6D9MCDgioqqBAgAWMgDhAgA/AAAzwP8KioxqmpNICoNKIDtFQGAhKiihAgDVPEDzwD8hAgAxAADFXTAFXW1UHX1FUSHFHGz1w+1Ubmv3fX/V/2PV+zwKqquUbXVFXXVVXCVFUW3ELHB3LGwG8Gr1eG/F/Cvd/D/LbiqFbX3VbBfUUWXVYH1VUHVcID0ZfOvfeHvd/0MH90xmoEBVXWVVUHXFXX1FEH1FEWT1IC0VeGvde2/3+F/Vfw9uZrBHUx1VXVVVYVV0QV11QVEUATEVOBfVPFvFFVRfGH0KZmtVP1/VeD3FeH/UfF/FcEP/ID4/6Pw/IHyPAHwN/0D1/3jVey/V+EvFf3/VfE/9DVDzIH6/6H6/KH6/+P++v2r9/yr1/0/VfGXf+EMV/0/1MFfv8Hw/6H7zKH6/zP/y/2rCv0r/68439C+/68M/ew8FY38VPGiv/2rFvELzqGvzyC6LwP6Kuq6arquIOouKaCsKUquhPAiKvKrJ/2D/6P+CqKr+qKLVIXFFdX/VYVfVYH/VcHwUYT186/994/+/4/21+/+16//VcXXVcD/VYX/VYW/RNX/UNH/Oquu/5/+/6/m9eD/7fz/VYV/VbX/VYX/VYX/VYBfcIDfKor+/2+p/6v3P63/v7H/VdX/UIWVVYT/VYX/VIX/VID//6rh3J++/+/u38f/2cv/VdDVVYX9VYVfUIV/UYVNVMF9fIDw3Jf+/5/yf9NeZflf/K88/6Dd8y/984f5FYXwhKiqCCCDSMCruAAIP4AA/6Py/6y+/bC+/60+/6/y/Y3+v/Giqr0LpvILP6Gu+oqqOyv6/K/+/6C//6/+/6/61YXChKiKqoqoqoKquqOu7qGq/6H6/+/+/6///+P//e/+18XyvKH6v6OqvqOq/rGr/qGu/qH676q/2qq/L+q/7rO/GfVTP6P674P6/qH6/6H+9v2r6/2r/L/6/7/6/7/6/7/6/7/6/7/6EqqtqoquqoqP/++x/6/u/7/6P4C2/4+y/7/6/L/60L/6GqCuqpq5quqf/6z//6+6/7/6/7/6/7/6/4/6/4D6f4C6Kqqtqiq5qqof/6/t/4Px/7/68w/6/7z6/7/6/7/6/7/6GIaBqpququq//YP9/4/q1bX61TX6VYE117X6VQX63TH6EKCcqlqtplqRn22k/6/6FKCNBaCtEIUNECCpEKCoioCqCiICW8KzjgAwCMADiqICqqo9qpqtqpotqqoxqkqspPGCRP2LVP2LD6D+7gKrCiKrurq/r6rXqqu/uqq/uvqfjIH8D6P7z6H6/rH61/2rivCD/+++/6++v6+u/8+9/4+6hKgi6oKrav6r/6Or6oKqriKu/6+5/6+tv6/+/6+u3CD4hIiKCKCrp/Gj7oKu/6Cq6oKqAASgAASAAASgACQgpgioAJaBAAQAAQQgAALVqKLRogJfACSoAASIAASAAAQAlgmoAISCAASAAQAgoILVAALFAAJfACSgAASAAAQgAAQgpgqoAJSBAASAAQQAAALVAILVAgJfpgqopgioJgIoigqoogqoAKSqAAQAAAQgqiLUqoLBqgJfCqSqAJSBAISqAISqRgiqVoCipgqopgqoAqrRoqrUAqpfAASAAASAAASgAASApgqoAAShAEQBAYQqoALFAKLVIgJPUUQgUUQAEQQgAAQAFQKoERQqQQQAAQQACKLVgALVAAIfACDVCALVACJVoALRAIjRAALUAALXFIS2FQW1FYQTf7/2AAJRAALRAAJVqILQAqjFAILFAgLQFYWzFYX/EQVXf7/7CAJPIgJfAAJfqgJVAqpfAAJfAAIff7+2f7/6VIX31bX/AASgAASAAASgAASApgqoAJSiAAQAAQQggCLUCILRCgJfAASgAAihAAiAAQgBZAmogpiBAAgAEEgBAgpRCArUKipXAASgAAiBAAAhAAgAlgqoCFAiAAihRQgBAArVAILVAApfZQqoqgGopgioqgioKgqoAKihAAgAAEgBqgLQqgrUqgpXgJaiAIqhCpiBCIqhVKqqhoqqqgiopgqooqrRoqrViqpfAASoAAihAAiAAAiBZgqoAFABAIihAZihAILQiKrQIApHEEQgFVSBEUgAAFQBVgmoUVghRVQBEAgBAALViAoVAAoPAALVAADRAAJVAALQAADRAALQAALRFEGwFVG1FUWXP7/2AgLVAAJUAArVqorAAqjQAgLEAArVFdG0FQD3FUSVP7/6KAJfKgpfAApdqgpfIqpfCgpfAArPP7+q/b/6VYD01YXfagqopgqoWgqoqgqoKgqoAJSiAAgAAASAqqJVqoJVqgpVlgKoigqhqgqoqgqoKgmoAJSBAAgAAAghqgpVqgpVqgpVqgKoqgqoqgqoqgqoigCoAJQBAAQAAAQgoiLVqoLVqiJfqgqoqgGoqgqoqgioKgqogJAiAAgBAAgAqgLVqgrVqiJfAJSiAICBABSqgIqClKiqlIqqqgqoZgKoIqjRoqrVKqpfAAgAAAgBAAgAAASoqgioAFQBgFSiAZQiAILQgKLRgAJfAEQgABSAAESAAFQgWgaoAVQBEQQABQQAAALAgALAAAJPqgJVqgBVqgBVAALVAADQAALUAALQVUG1VUCaVYW51b/qqoJVqIpVqoJVqILVCqDVAALAKgLAVYWWVUG/VYSd1b/6qgpVqgpVqgpVqgJfIqhfAApfAAIA1Y/61Y/6VYX/V4X/gJaqgKSqKpSBAJYClqiqVoKqpgqoZgKoAKrVAqrVAqpfqoSqqoGqqpChgKqilIqqpoqgpgqoqgqoAqrVqqjVqqpfgIaqAIqqKKqiqJqqpqCqigKhqgqopgKogqJVqqrVKqpflqKqlKGiqpiqgqqqgqqqqqqqqgqoqgaoiqLVqqrVqqpfVoKqqoGqpoqqqoqqApCqgISqigqoqgKoqqhVqqpVqqpVqgqoqgioqgqoqgqoKgqoAFQBAEQBAJQhqgJVqoJVqgJVVQKopAGoVgioqgKoCAaoAFQBAEgIAAQAqqLPqgLRqgITAKjVIKjVAqDVAKrVqgBVqgJVqgLfVbW2VLW6VYW7f7U6AKLVIqhVAqpVqqrVqqpVqgJVqgLVVdXXVcV3VUVV/4VXIqpfKqpfAqpfqqpXqqpVqgLVqgLXf7VwfzXBVYVU1TdVAASoAASAAAQAAASolgqoABSCAJShkZSiAILUgILFggJfAAQAAAABAAgBAASgpAmqAFiBAJQhQZiiAApVgKrVgKLfAASoAAihAASoAAihVgCoAFQBAJShgZSBAALVqoLVqgJXpQqomgGoWgioqgqoigqoAFShAEQiAJgqogLVqqrVqgpfAlQCAEoBAFQhCESqWCCqVgiiVICilqKqggDEgqrRgqpfAFQiAICBAKSqAJSiVoCqlACqZgqoVoCqAKjFoqrVoqpXUVQqRZSiBVQqAJQiVVSqVgCqpgqopgKooKjRoqrVIqoPAALAAADRAALVAADVAADUAKDAAKLXVES2VEW1VUBXf7/2gALFgIDVgoJVqIrRAojFAKDFKqrUVcW2VYX3VIGTf7/3ggJfgKpfqoJfqgpfgqhfAqrfAqoff7+2f7/6VYX334f/BVUgUVQAFUQAQEQgVkGoAVQiUQQAEQQAAKLAAAIAAAIDVUUgVVEBVUQAVVQgVVGoUVQBUVUAAQiAIAoAAAoAAAIDAFQgEFWBAVUgEUQBVQGoVVQBVUQgAQQAACLVKALVAALXphKoVkmoaQaoaUWoRhSoAVQBERQAAASAqgIVqgpVqoJVAVQiVVABUVQBAVQiVpWqVQSqVQSolgKoAqjAgqrAAqoPVQWgVVSBVUSAQESAWgWoQVQBEVQBAVQBAAIFAAIEAAIAQAQARRSBRUQAABQgWgaoAFQBAVQBAVSBAALVAILUgAIPAADAAADAAALXAABVAADBAAIAAALUUES1UQB0UIADPL81AALAAAIBAALVqAJVAqrQAALAAALAUEBRcIR3UEBEf0P1AAIDAAoDAALfqoJXAqoDAAIAAAIAc7Oq8IDZUID18IBdAADAAADVAADVAADAAADRAALVAADXFXW1FVWFVUSQf7/yACBVAADVAADVAADQAADBAADQAADVFbEVFVAFVUAFf4wiAADVAADRAADVAADVAADVAADUAADcVbW1VUFVVUWV/7/1AADVAADVAADVAADRAgDRAADVgADAVUG1FUUxVYUX/7/AAALVAADVAABVAALVAADEAADEAADXVHG1FFWBVEG0/7+iAADAAADVAADVAADVAADQAALUAALQ1UW1UQSAVYWi/7+qFXSVVbExVbXVVUE1VAWx//W0V/GvVPGvV/Vrf++pqqqpFXUFVUEAVbW1VUE1VLGFVYWAV/GuVPEPVzEgEiDoKiosVcUYVcC0VYWVVcUUVYWYUICA/1u6OxMMG+LwECj/KgrPf7+6/7+6f7+6f7/wf7/qfL+qKqqsKoqAGKIDOqr8O6vMAAJFAALVAALVqALFAqjQAALVAALRVcWXVcX/VVWXP7/3AIJVAAIBAALVqALVIqhVAApVAALdVdW3UYX/VVDVf7f7qgJVqIJVqAJVqgLVAKhVAALFAALQVYW6VYFfVYVV37/dIKLVCqjVAqLVqqLVqqLVqALVqgLAVIWaVUX/VYWXf7/7AALVACJVACJRqALVAqhFIqLVAqrUVNW/VYVzVUHXf7/ZAAIAAArVAAJVqgLVAqjQAALVAIIVUMCzVIR/VYVB/7/1VcSTVYA3VcXfVYUzVcW7VcUx/68M84cNErD3P8f/KjZfVMXXVcDTVcX3VYXfVcVDUIC1/4fs/4/+3///P+H/7vrvV0XfVYX/1YXfXYX3VYX/VIC19/P/////f/f/P+//GvrvP7/6/7/6f7/6f7/zf7/6/7/5KsKv6/qvJvJv/9/+/2/tIgJfAAJfAAJfqgJfgqpfAAJfAALf/7/2/7/6VfXTVbX/AAJfAAoDAArfqgJfgqhfIgpfAALf/7/6/3/6VcR3XwXfqgJfqgpfqgJfqgrfAqpfAAITAAIA/4+6/4P61YH/1Y//oKpfoqhfCqpfoqpfqqpfqgJfqgLf/7+6/7/6VcXXVbX/AgJfAgJfIALQqgJfAqpfAqpfAqof/7/y/z/a18f3dcX/AAIVAApVAAJVqgJVAqoVAAJHAAIN1zfwVQX6UITwf0Nf/78w/78w/791/78w/7/w/T/wGKqJEFCJEKBr/wOpPy/5/7/69b/6/4z7/7/6/z/61TH6EKCuqvqvqvK//+39/6/CV7X31b/31YX/Xf3X1c3/cIDzP4+s/0+9+/Pvf8///y/+X73ff7/7/8/bV7/7/w//8AD/EKD8/xPxv4P+/////4//ABSgABCAABSgACQgBBCAWRahAFQBARAgACChqKYIogSgAASgABSgABCAACAAABCAZRaQABCBARQgABABAASgAASAACSgABCAACQgABAgBBCAmRWgAFCBARQAABChAIYIAgSgBCCABBCAABCgEBCABBCAVSWgAFQJABQgASCgAIQAoAqimgWgWRqgVhWgRSWgphqgliqgBFABABAAABCBqgqopgqoAESJAFCJABSpABChBBCJVRWqRVVClQWgqhagAISgIoqqARQgARAAARQgACQABBSAVRWgAVQBAVQBABCpgASAAAiiARSgABCREBShEBUhFBChVRWRAFChRBEhURUgUVSAAQSAAAQAAAYIAASAAIQAVgooAISBIgQAAAQAgKLVCALVAAJfCASgIgQgAASgAAQgZgqoAIQqAAgAAQSAiKJfAIJVAIJVABSgABCAABSgABSgBBCglSWgAFQJARQgACCgKISAKgqiABSgABChABCAASABBBCAlhmRAFABEBABABCACAohKiqhACSgABCAABAhABAABBCAWhqgAFCpQRABABCQAIiAAAihQRCAACQgBBCAABCAABCAlSmgAFAFAFABARBQAAgBCAiBlRqglSqhWhmhWSqgKSqgihqgABCCBBCAABAApoqoqgioAFCqAFCqAFCBAFCJBFCKFRGpVRCgWikgmSqgiKiiIIqiEBQgFVCAERAAABABUBAAVVmgRVABEFABAFCBiAgBAAihQBVhABFQFRCABBCRBBCBWhlUAFCVARBhAQEQUVgBVRSBAgQAAAgAAAoBAIgBZgoIApgKAAoAAQgBAArVAALVAAJfKAQgKgghAAghIAohpgqoCqghAAgBEQigAAJfAIJUgopVABCAACCAABCAABCAABCAVRWgAFABABSAVRCgAISAAAqiAASEABCAABCgABAAABCAVRGRAFABABAgARCAAAohAAqiABAAABAEABAgABCAABWgVRWRAFAAABQgQRSgAIaoCCqqABCAABSgABCAACAAACAAlSqgAFACACAAERAQAAoAKCiAVRWgZRChVRWglSqgkCqglCqgAFCBBBAABBAApgqoqgqoAFAFAFABAFAFAFCqAFEKVRVaFRGqlSqglSaggKQBgKiiABQgABCAABSAABAgUBQglVWgAFAFAFQBAFAqgAYgAAgAQBSgUBCAFRCQACChACAhVRpQAFAaACBQASEgUVQoaQSgAIQIAIqCAIQAAIgAWgoIAFoCKggBCAQAIILVAADVAAJfIAqiAAqiAAqiIAQgqiqoAKoBAAiCJSSgAAJfooJVKqJVhRaglSWgqhagmSqgliqgghigAFCAABQAABABpgqoagqoqgWgqgCgqiGglSqglSqgIBqgAFAFABAgABCFqgmoqgqolgqglSqgqSqgqQqgqgWgihigAFCBABQAABABqgqoqgqokgqghiqgqimgqiqgmiqgCCqgAFAFABAAABAFqgqoqiqoaiqgqhqgKhqgKhKgKgSgmhGgAFABABAgABCAqoqoqgqqAFCJAFCJAFCJAFCJAFAFFVVRVVVhFRWgWRWgAIABKICiVRQABBQgABAAABAAQBAAVRWgAFAFAFABAVAFAAQhAAiBABAhABAgABCBABABQBCgVRVQAFBVVRCQFREAAESIAAqgogqIqgqomgqoqgqoKooIAJQCAAoIAIoCqqJVogBVqgJVqgqoqgqoqgqoqgqoqgqqAJQhAAQAAAagqAJVqopVqqpVAFSpAFCJAFAFAFSqBFCJUVWqVRWgmRWgliWggIShgpqiAFSpAEAFAFAJAFCqBFCqQFCZECWilRmglSmggIiKgKiiAFSqABCpAFSqAFCqBEEFFRBVVRSgqQWgqgWgqpCiqqCiAFCFEFQpEFCJAFCpAFCqRRWpVUGiVSqglSqggKqigKqiVFWqVVCpBVUFURGqEACqFFCKFQGglgqgliqglqiKmqqqVFWqVRCpVQWqVRWqVACqFRGKABCiJhYAKiqgqoqoqoqqVVWgVSagpRWgVSWgVhagBFigABABBFABAFABpgqoqgqqlgVglSpUqgWglgqgmgqQFBIgAFAFAFABBQAAlASopgqogJQKgJABiqQhgJqimKAClgiqqgqoqgqoIqrVgoDRAKpfgpSqgIoiqqSqiKqilqqqpoqqqgqopgqoIKJfoqpVoqpVBRQgQVQAFVQAAFQgVBEAVVWgUVQBAVQFAFCJgASoAAiCVVUgVVEBVVAgBVQgVBEAVVCRUVUBAVCFEVCKAAoBAACgAFQgAFSBAVUgEVQAVBUEVVVVVVAgAUQEQEQFKAAhAACBABQAUBAgQBQAQBAAABEABVWhEVQBAFCFEVCqAAohAISiVRWgVVqhVRUAVVUgWiagVlagFBABBFAFBFAJpgqoqgqoVVWhVVCBVVSBQFSBUFAFVVVRVVWgUVWZUUGaACABAESiQFQFRVCBBVAFAFQhUFAFRVWRVRVhVRWgVQGpAIQBiKihFVRZQFCZEEBVBFCaAFAJRVFaVRWZmRlglQWgQFQBhZShAAQAAAgBAAgAAAgBVgoIAFQBAFQBBZQBAILVAALEAAJfAAggAIgBAAgAAIiipgqoAFQBAIQCgZSiAAJfAILVgApXUEVhQBRgFRVRBBVRVBCRVRVVAFQhVRVQARUgUVQAVUSgVRSQVRBVVVFUQBFRRBFhZRBVRVRVURBQQRAAVVghVVShQRVhARVVVBVVVRFRFFBgVVVVAFERVVBVEUQAVVYhVVShQBAQABGFRFChQBBUQBFBVRVVAFBZFRVQVRAgQVQhIVSgVhVgWhpQVRqgWRVQWhpgVRmQABCRQBQQBBQAVQSoVQWoAVSZAFCVBFRaBFCZQFCpVRVpVVFZWRpQaRWgVVQBaVqiQBVQVVBRVRVQEFVQUBAgVVVgURAVAVBRAVEBUVQhVVQARRVgVVVAVVUAVRVQUVQgVVVQQVAUAFBFFVEFRUQBVRSARUQAUFQCVUQAVFQAVUUIQFQCVQQAKAoIgILAACDQAAIDVUUgFRQgVUQgAFSgVgWoVVQBVVSIAQSgAAIAgAIAqgIAAAQAAAQIAAQAAAQAFgAIAFQBAAQAAAQIgKLVAADVAABfAIQIAAgAAAQIAAQARAkoAFgBAAQIEQgICAJVAAjVAADfAAQAAIQAAAQAAAQAVAAIAFQBAAQAAAQAACJVAABVAABXQQAAAACIFAgACggIAgAIAFQBAAgAAAQAioLVAADVAABfAIQIAAQBAAQIAAQBVAAIRAgABAgISAIIAKrRAADVAABfAAQIAAoAAAQAAAQAVgoIAFQBAAQIARQAIALVAABBAABdVZQIVVQAVFQAEUQAVgEIFVQBUVQICQoAICLUAAARAAAfAADVAABRAABVAALVAADBAADVAADQVcW3VcW1VYG3f7/2AADVAADVAAJVAADVAADVAALVAADVVUW1VUWLVYWR/7+iACBfAABfACBfAABfAABfAAJfAAADfb+6f7+qVYW+14WqIgSgCAQgAAQgIAQgpgqoAJQiAAgAAQQAAKJfioJRAIJVAAqiAAohAAiBCAggqgmoIpgBAAgISQggAApfiApVAApVIAQgKAghAAggAAgBpgqqAKYBAAggAQggAAJfqKLVACLXpQqoqgGoqgqoqgqoqgqoAJQhAAgAAAQAqgJfqopVqAJVIpoiCpqBIJoiKAQqaqKqZoiqmgqopgKogqpfoqpVAqpVAASiAAiBAASiAAiglgqqAFQBAEQBIZgiAAJfgKJTIAJVUUQgVVQhVUQgIEQgVgaoEVQhRQQAAQQAAAIXqgoEAALDAABfAABfAAJfAABfAABfAAJfAADX/w/w/z/wV8UXVcXDgIJdgIpdqoJVqopdAqpVAAJfigoQXcXX34/3VUXXXwf/CIJVAAJfAAJfqgJfAqBVAAJfAAIEVw2w1Y3/VYX91YX/AESAAFCAAESAAEQABFCAEUSBVVVAAEAVAECBAACAoiiqAFSAAFSAAFCAAEAAAECAAECAFVWAAUQFAECBQECAACKKAECAAFCAAEQAAECABFCAEVSAVVWBAFQFAFCBAFCAIhqqAECABFCAAFCAEFCABFCAEUQAVVVBAEAVAUCAAECAoiqqAESAUUCAUFSABEQABFCAFEAAVVWAAEAVAECBAECAqBCqVVWBFVWAFVWBFVWBVVWAVVWAVVWABUQFAECAAECAqiqgAFQFAUAFAFQFAEAFBESFAFQFFVWFVVWFVVWAQECAABCqAVSAAFCBEFSBEEABFFCBVVWBVVWBBFEFEVUFAECACBKAAACAAFCARECAAECAQECAAESAVVWBQEAFQECAAFCAqhqqCCiiIhAgAhiiKCQgCBCqWSWgAFAJCBCABBQhAISAgIQIAFSAAFCAAFSAAECABFCAFUQAVVVBAUAVAECAAAAAKiqqAFSAAFCBAFCAAUAABFCAFECAVVWFEFAFAECAQEAAKiqqAECAAECAAFABAECAAFCAUFCAVVWBQVCFAFCAAFCAIBCiAVCAAEAAAFCAAECAAFCABEAAVVVFAFAVAUCAAEAACCiKFUCAFUABEFCBEUAAAEAAAFCAVVWABECFAECAAECAoBAoVFWAVVWAVVWAVVWAFVWAVFWAVVWEEEAFAUAAAEAAqSqqEFQFFVCFEVAFAEAFUEAFBVAFVVVFVVUFVVWAQACAAFCqAFWBAFCAFVCABECABFCBUEAEVVWBAFBFAUEFAECAqBKBAACAAECAQEGBAECAQFCAEECAVVGAAFABAFCAAECAoBCWKCAgKhAiABAoohohAhAgWiqgAFAFoBCgAREpAIgAgooBAFCAAECAAFCAAECAAFCARFWAFVWFAFSBVVCAAFCAChqqAFSEAFCAAFCAAECAAFCAFVWBVVVVAFABARCAAAAAKAqqAFCAAFCEAFCAAFCAAEGAVESBVVWAAFQFQUCAAECAKiqqAFCAAFSAAFCAAEAAAEAAFUAAVVWAAEAFEUAAAECAKiiIUVWARFWBVFWAFUAAFUAAFUAAVVWABEAFBECAQECAKiAKFVVBVVWFFVWFUVWAVVVAVVSAVVWAFUAFFUAAAAAApSmoAFQFAFCBAFSBAEAFEEAFFUAFVVVBUVWFQFWAAECAAFAKQFSAUFCAFVCAAECBAECBFUAAVVWAAEAFAUEFAECAKiqgAFCAAFCAQECAQEAAAEAAFUCAVVGAQEAFAEAAQAAAKiJWIhqiCBqqABqiIiAgKiKElSqQAFCGIiCgABkBqoSgKqoAFVCABEEAAFCAEEAAAEAAAFCAVVWAAESFAFCBAECAKBIqAEWAAECAAEQABUAABEAARUCAFVWAAFAVAFCFQECACigKEECAFUAQAECAAECAAFGAAFGAVVWAAFAFAFABAECAABKKAECAFEAAAEAAAEAAEEAAAEAAVVWAAEAFAECFAECAICAGAEAAAFCAAECAAEAAQFWAEFWAVVVFAFABAFCAAECAIhiqVVWAVVWBVVWAVVWAFVVFFVVFVVWFAFWBQEWAAFAAagWqVUQFBEQFAFCFAECFQFAFAFWBVVVFVVVVFVBFQECAABCJAFCBAFCAAFCBAFCBQFCAVVWAVVGFVVCBFVEBAEAAABqoQUCAQECABUCAQFWEQFCAFEWAVVUFABCBQFCAAFCAqQKWABAAABCCgBAAABAAABqqVRWqAFABAhqgERgqAIqiAKoKVVWAVVWBVVWAVRWAVVWAVRWAVVWAAEAVAECAAECAqiqiVVWBVVCBVUVAVVWAVFWAUFWAFUWEBUAFEUAQAEAAmiqoVRWAVVWAVVWAVVWAVVGFVUBBVVWEAFUFAECAAECAqiqqVVWAVVWAVVWAVVWAVVWAVVWAVVWAAECFEEAAAEAAqSqoVFWAUFCAFVCFVVWAUBGAVVWAFFCAAEAFBECAAEAAmiqoVFWAVVCAVVWAUVWAVUWAVFSAVVWEAEAFAECAAEAAqiqIEESFFUAFAVCFEEAFEEAFAEAFVVVFVVUFVVWAAECAABCqFFWAFUAEAFWAEEAAEECAQFCAVVWBAFAFBUAFAECAIBKAEACABUCAAEWAEECFEECAAECAVUWAQEAFQFCAAEGAgCiGmiqglSqgqiWgmiqgmiqgKiqgAFAFABCAABAJpgqoqoqoBUQFQVQVFVQVAEQFVEEVRVQVVVVFVVVBVVWAVRWAAFCqVVWFVVGFVVAFBVAFVEEVVVAVFUVVVVWBVVWAUBWAAACqAFQFAFCFAVWFEVQFVFUVVVBFVVWEVVVFVUGARUCAACCKAEQVUFAFQFQFQFAFAEEFEEAVVVVFVVUBVRWAVUGAAACqVEQVRVAVVUQFAFQVQEAVFFAVVVUFVVWFVVWAVRWAAFAKVVUFVVWBVVWAVVWBVVVFVVVBVVUVVVWBBRGAAACApYGqVVWBVVUBVVUFVVUFVVWFVVWBVVWFUVUFUUSAUECAGiqqVVWBVVWAVUWFVVWAVVWBVVVAVVWAEUAFFUUFAEAAqSqgVRWAVRWAVVVRVVWAVRWAVVWAUUGAEEAFEECAAACAmiqQAJAqABCKAFAFABCqAAAGUACWUBiqmiqgmSWgAKQBiKgBUFWBAFQAEVWBBEWBFFCBVVUFVVWBVVVFAVUVAFAVFBagVVSAFVCFVVCEQEEBRFGBRFSFVVVBUVAFQVAVQUARCRigQVWBAVFFVFVFVVGBFFCAFUVVVVWFVVBFEVQVAEAEGCahQFCAAEGFBFCBAFCAQFGBRVEFVVVBFVUFVUAFAEAQqSqgRFSAUFCABVAAQFEAQECAFFCAVVWBQFQFBFQVQEABEigAVVWAVVWBVVVAVVWBVVWAVVWAVVWAQVAFAEAVAEARahqgQFWFVVCFVVWFEFEFUFAFVVVFVVWFVVVFVVVFEEBAUVAJRVUFVVUVVVUFVUUFUVQVVVUVVVVFVVWFVVWBVRWAAFCCQVAFUFBVRVAFQFQFQEAVUEAFVVUFVRWAVVWAVRWAAIBaCVIgEBAgAFAgABCgABCEVRWQAFCEAUCgEVEJgASoqgoAAESAAECAAECAAESAAECAQUCAVVVAAECFAECAAFCAYhqqAFCAQACAAECEAECAAFCAQFCAVVVUAFBBAECAAACASBmVAFRAAFBAAFRAAFBABEAAEECAVUWAAEAFQECAAEAAVWpaAECAAECAEECAAEBAAEBAQEBAVVVEAECBAFBAAACASFlVQECAAEBAAEAAQEBAAECAAECAVVVAAECFAECAQECAahKKVVWAVRWAVRWAVVWAVVVAVVVAFQGEQEAFAECAAECApSWSAFAFAEBFAEBVAECFAEBFQEBFVVVVVVWBVUVARUGARVFZAECAQECAEECAAEBAAECAAECAVUWAAEBFAEBFQEAFaipRAVBAAFFAUEBABFBAAUWAUEBAVUVAAUAFBUQVAUAVWRpQSRVRYBEVFRBQRRVRRBAhVRlQAFBZURBQABCBUVSgVVQCKhCgCBIiABAgIBAgABAgZRVgAFABABAAABAiqoaAAIQIABqiABoiACiACiAgChAgahpQAFABChAgIiAAiAqhCAABIBAgKhAgABAgABAAACoqlSpiAFAqACogACggqKigACABCBAgICCgABAgABAgIBAgZhVgAFABABAAIBAgqIohAAQAZhpgaiogpSqgaiUgaiqgphogAFABABAgCCAApoioFAgIAFCqAFCqABSqAFCpAFAKVVVqVVViahogmipggKABIBQBIRAgKhAgABIgIBAgIhAgZiVgAFABAFABAFAKqgoBAAQAKBqiKhBAABpqICBQIioiKipQABAaIiBQKSggVUShaEQAgIQIgIoCqoQAgIoBqoqIAKQCigoICQoBAALfAABVAAJdCIQAAAQAAAQAAAQARAAIABQBAAQIEVQAgAJVAABVAAJV';
    $data = base64_decode($data);
    $dirs = [[0, -1], [-1, 0], [1, 0], [0, 1]];
    $numbers = array_merge($goal[1], [0]);

    $result = [];
    $encnum = encodeForSecondRowSolver($board, $numbers);
    while ($encnum % 11880 != 0) {
        list($x, $y) = locationOf(0, $board);
        $i = ord($data[intval($encnum / 4)]) / pow(4, $encnum % 4) % 4;
        step($x, $y, $dirs[$i], $board, $result);
        $encnum = encodeForSecondRowSolver($board, $numbers);
    }

    return [$result, $board];
}

function encodeForSecondRowSolver($board, $numbers)
{
    $encnum = 0;
    $cells = range(4, 15);
    $scale = 1;
    foreach ($numbers as $n) {
        list($x, $y) = locationOf($n, $board);
        $c = $y * 4 + $x;
        $i = array_search($c, $cells);
        $encnum += $i * $scale;
        $scale *= count($cells);
        array_splice($cells, $i, 1);
    }

    return $encnum;
}

//////////////////////////////////////////////////////////////////////

function dirLRandPackR($y, $board, $goal)
{
    $bwFun = function ($x, $y) {
        return buildWallsUL($x, $y);
    };

    $result = [];
    moveTo($goal[$y][0], 0, $y, $board, $result, $bwFun);
    moveTo($goal[$y][1], 1, $y, $board, $result, $bwFun);
    moveTo($goal[$y][2], 2, $y, $board, $result, $bwFun);
    fixRow($goal[$y][3], 3, $y, $board, $result);

    return [$result, $board];
}

function fixRow($n, $tx, $ty, &$board, &$result)
{
    $bwFun = function ($x, $y) {
        return buildWallsUL($x, $y - 2);
    };

    list($sx, $sy) = locationOf(0, $board);
    if ($sx == $tx && $sy == $ty) {
        step($sx, $sy, [0, 1], $board, $result);
    }
    if ($board[$ty][$tx] != $n) {
        moveTo($n, $tx, $ty + 2, $board, $result, $bwFun);
        $walls = buildWallsUL($tx, $ty);
        $walls[$ty + 2][$tx] = 1;
        if (moveSpaceTo($tx, $ty, $board, $walls, $result) === false) {
            return false;
        }
        list($sx, $sy) = [$tx, $ty];
        $moves = [
            [-1, 0],
            [0, 1],
            [1, 0],
            [0, 1],
            [-1, 0],
            [0, -1],
            [0, -1],
            [1, 0],
            [0, 1],
        ];
        foreach ($moves as $m) {
            step($sx, $sy, $m, $board, $result);
        }
    }
}

function dirLR2($y, $board, $goal)
{
    $bwFun1 = function ($x, $y) {
        return buildWallsUL($x, $y);
    };

    $bwFun2 = function ($x, $y) {
        return buildWallsUL($x + 1, $y - 1);
    };

    $bwFun3 = function ($x, $y) {
        $walls = buildWallsUL($x, $y);
        $walls[$y + 1][0] = 1;
        return $walls;
    };

    $result = [];
    moveTo($goal[$y][1], 0, $y, $board, $result, $bwFun1);
    moveTo2($goal[$y][0], 0, $y + 1, $board, $result, $bwFun2);
    if (moveTo($goal[$y][2], 1, $y, $board, $result, $bwFun3) === false) {
        return false;
    }
    if (moveTo($goal[$y][3], 2, $y, $board, $result, $bwFun3) === false) {
        return false;
    }
    if (moveSpaceTo(3, $y, $board, $bwFun3(3, $y), $result) === false) {
        return false;
    }
    list($sx, $sy) = [3, $y];
    $moves = [[-1, 0], [-1, 0], [-1, 0], [0, 1]];
    foreach ($moves as $m) {
        step($sx, $sy, $m, $board, $result);
    }

    return [$result, $board];
}

function dirLR3($y, $board, $goal)
{
    $bwFun1 = function ($x, $y) {
        return buildWallsUL($x, $y);
    };

    $bwFun2 = function ($x, $y) {
        return buildWallsUL(3, $y - 1);
    };

    $bwFun3 = function ($x, $y) {
        $walls = buildWallsUL($x, $y);
        $walls[$y + 1][1] = 1;
        return $walls;
    };

    $result = [];
    moveTo($goal[$y][0], 0, $y, $board, $result, $bwFun1);
    if (moveTo($goal[$y][2], 1, $y, $board, $result, $bwFun1) === false) {
        return false;
    }
    if (moveTo($goal[$y][3], 2, $y, $board, $result, $bwFun1) === false) {
        return false;
    }
    if (moveTo2($goal[$y][1], 1, $y + 1, $board, $result, $bwFun2) === false) {
        return false;
    }
    if (moveSpaceTo(3, $y, $board, $bwFun3(3, $y), $result) === false) {
        return false;
    }
    list($sx, $sy) = [3, $y];
    $moves = [[-1, 0], [-1, 0], [0, 1]];
    foreach ($moves as $m) {
        step($sx, $sy, $m, $board, $result);
    }

    return [$result, $board];
}

function dirLR4($y, $board, $goal)
{
    $bwFun1 = function ($x, $y) {
        return buildWallsUL($x, $y);
    };

    $bwFun2 = function ($x, $y) {
        return buildWallsUL(3, $y - 1);
    };

    $bwFun3 = function ($x, $y) {
        $walls = buildWallsUL($x, $y);
        $walls[$y + 1][2] = 1;
        return $walls;
    };

    $result = [];
    moveTo($goal[$y][0], 0, $y, $board, $result, $bwFun1);
    if (moveTo($goal[$y][1], 1, $y, $board, $result, $bwFun1) === false) {
        return false;
    }
    if (moveTo($goal[$y][3], 2, $y, $board, $result, $bwFun1) === false) {
        return false;
    }
    if (moveTo2($goal[$y][2], 2, $y + 1, $board, $result, $bwFun2) === false) {
        return false;
    }
    if (moveSpaceTo(3, $y, $board, $bwFun3(3, $y), $result) === false) {
        return false;
    }
    list($sx, $sy) = [3, $y];
    $moves = [[-1, 0], [0, 1]];
    foreach ($moves as $m) {
        step($sx, $sy, $m, $board, $result);
    }

    return [$result, $board];
}

function flipStrategyDirection($strategy, $y, $board, $goal)
{
    $board = flipLR($board);
    $goal = flipLR($goal);
    $result = call_user_func($strategy, $y, $board, $goal);

    return $result === false ? false : [$result[0], flipLR($result[1])];
}

//////////////////////////////////////////////////////////////////////

function moveTo($n, $tx, $ty, &$board, &$result, $buildWallsFun)
{
    list($x, $y) = locationOf($n, $board);
    while ($x != $tx) {
        $dx = $x < $tx ? 1 : -1;
        $sx = $x + $dx;
        $walls = $buildWallsFun($tx, $ty);
        $walls[$y][$x] = 1;
        if (moveSpaceTo($sx, $y, $board, $walls, $result) === false) {
            return false;
        }
        step($sx, $y, [-$dx, 0], $board, $result);
        $x += $dx;
    }
    while ($y != $ty) {
        $dy = $y < $ty ? 1 : -1;
        $sy = $y + $dy;
        $walls = $buildWallsFun($tx, $ty);
        $walls[$y][$x] = 1;
        if (moveSpaceTo($x, $sy, $board, $walls, $result) === false) {
            return false;
        }
        step($x, $sy, [0, -$dy], $board, $result);
        $y += $dy;
    }
}

function moveTo2($n, $tx, $ty, &$board, &$result, $buildWallsFun)
{
    list($x, $y) = locationOf($n, $board);
    while ($y != $ty) {
        $dy = $y < $ty ? 1 : -1;
        $sy = $y + $dy;
        $walls = $buildWallsFun($tx, $ty);
        $walls[$y][$x] = 1;
        if (moveSpaceTo($x, $sy, $board, $walls, $result) === false) {
            return false;
        }
        step($x, $sy, [0, -$dy], $board, $result);
        $y += $dy;
    }
    while ($x != $tx) {
        $dx = $x < $tx ? 1 : -1;
        $sx = $x + $dx;
        $walls = $buildWallsFun($tx, $ty);
        $walls[$y][$x] = 1;
        if (moveSpaceTo($sx, $y, $board, $walls, $result) === false) {
            return false;
        }
        step($sx, $y, [-$dx, 0], $board, $result);
        $x += $dx;
    }
}

function buildWallsUL($x, $y)
{
    $walls = emptyWalls();
    for ($i = 0; $i < $y; ++$i) {
        $walls[$i] = [1, 1, 1, 1];
    }
    for ($i = 0; $i < $x; ++$i) {
        $walls[$y][$i] = 1;
    }
    // array_splice($walls, 0, $y, array_fill(0, $y, [1, 1, 1, 1]));
    // array_splice($walls[$y], 0, $x, array_fill(0, $x, 1));

    return $walls;
}

function emptyWalls()
{
    return array_fill(0, 4, [0, 0, 0, 0]);
}

function moveSpaceTo($tx, $ty, &$board, $walls, &$result)
{
    list($sx, $sy) = locationOf(0, $board);

    $queue = [[$tx, $ty]];
    while ($walls[$sy][$sx] == 0 && count($queue) > 0) {
        list($x, $y) = array_shift($queue);
        if ($x < 3 && $walls[$y][$x + 1] === 0) {
            $walls[$y][$x + 1] = [-1, 0];
            $queue[] = [$x + 1, $y];
        }
        if ($x > 0 && $walls[$y][$x - 1] === 0) {
            $walls[$y][$x - 1] = [1, 0];
            $queue[] = [$x - 1, $y];
        }
        if ($y < 3 && $walls[$y + 1][$x] === 0) {
            $walls[$y + 1][$x] = [0, -1];
            $queue[] = [$x, $y + 1];
        }
        if ($y > 0 && $walls[$y - 1][$x] === 0) {
            $walls[$y - 1][$x] = [0, 1];
            $queue[] = [$x, $y - 1];
        }
    }

    if ($walls[$sy][$sx] == 0) {
        return false;
    }

    while ($sx != $tx || $sy != $ty) {
        step($sx, $sy, $walls[$sy][$sx], $board, $result);
    }
}

function locationOf($n, $board)
{
    foreach ($board as $y => $r) {
        foreach ($r as $x => $i) {
            if ($i == $n) {
                return array($x, $y);
            }
        }
    }
}

function step(&$x, &$y, $d, &$board, &$result)
{
    list($dx, $dy) = $d;
    $n = $board[$y + $dy][$x + $dx];
    $board[$y][$x] = $n;
    $board[$y + $dy][$x + $dx] = 0;

    $x += $dx;
    $y += $dy;
    $result[] = $n;
}

function printBoard($board)
{
    foreach ($board as $row) {
        foreach ($row as $n) {
            if ($n > 0) {
                printf("%2d ", $n);
            } else {
                echo "   ";
            }
        }
        echo "\n";
    }
    echo "\n";
}

function writeResult($result)
{
    foreach ($result as $n) {
        echo $n . "\n";
    }
}

//
// Array utilities
//

function flipLR(array $arrays)
{
    return array_map('array_reverse', $arrays);
}

function cartesianProduct(array $arrays)
{
    if (!$arrays) {
        return [[]];
    } else {
        $tail = array_pop($arrays);
        $result = [];
        foreach (cartesianProduct($arrays) as $values) {
            foreach ($tail as $v) {
                $result[] = array_merge($values, array($v));
            }
        }
        return $result;
    }
}

main();
